/*
 jQuery v3.3.1 | (c) JS Foundation and other contributors | jquery.org/license */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(u,w,J){u instanceof String&&(u=String(u));for(var z=u.length,y=0;y<z;y++){var x=u[y];if(w.call(J,x,y,u))return{i:y,v:x}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(u,w,J){u!=Array.prototype&&u!=Object.prototype&&(u[w]=J.value)};$jscomp.getGlobal=function(u){return"undefined"!=typeof window&&window===u?u:"undefined"!=typeof global&&null!=global?global:u};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(u,w,J,z){if(w){J=$jscomp.global;u=u.split(".");for(z=0;z<u.length-1;z++){var y=u[z];y in J||(J[y]={});J=J[y]}u=u[u.length-1];z=J[u];w=w(z);w!=z&&null!=w&&$jscomp.defineProperty(J,u,{configurable:!0,writable:!0,value:w})}};$jscomp.polyfill("Array.prototype.find",function(u){return u?u:function(u,J){return $jscomp.findInternal(this,u,J).v}},"es6","es3");
!function(u,w){"object"==typeof module&&"object"==typeof module.exports?module.exports=u.document?w(u,!0):function(u){if(!u.document)throw Error("jQuery requires a window with a document");return w(u)}:w(u)}("undefined"!=typeof window?window:this,function(u,w){function J(a,b,c){var d,e=(b=b||B).createElement("script");if(e.text=a,c)for(d in Kb)c[d]&&(e[d]=c[d]);b.head.appendChild(e).parentNode.removeChild(e)}function z(a){return null==a?a+"":"object"==typeof a||"function"==typeof a?xa[Xa.call(a)]||
"object":typeof a}function y(a){var b=!!a&&"length"in a&&a.length,c=z(a);return!A(a)&&!qa(a)&&("array"===c||0===b||"number"==typeof b&&0<b&&b-1 in a)}function x(a,b){return a.nodeName&&a.nodeName.toLowerCase()===b.toLowerCase()}function Q(a,b,c){return A(b)?d.grep(a,function(a,d){return!!b.call(a,d,a)!==c}):b.nodeType?d.grep(a,function(a){return a===b!==c}):"string"!=typeof b?d.grep(a,function(a){return-1<ya.call(b,a)!==c}):d.filter(b,a,c)}function h(a,b){for(;(a=a[b])&&1!==a.nodeType;);return a}
function E(a){var b={};return d.each(a.match(N)||[],function(a,d){b[d]=!0}),b}function m(a){return a}function q(a){throw a;}function F(a,b,c,d){var f;try{a&&A(f=a.promise)?f.call(a).done(b).fail(c):a&&A(f=a.then)?f.call(a,b,c):b.apply(void 0,[a].slice(d))}catch(g){c.apply(void 0,[g])}}function M(){B.removeEventListener("DOMContentLoaded",M);u.removeEventListener("load",M);d.ready()}function ia(a,b){return b.toUpperCase()}function n(a){return a.replace(Lb,"ms-").replace(Mb,ia)}function r(){this.expando=
d.expando+r.uid++}function v(a,b,c){var d;if(void 0===c&&1===a.nodeType)if(d="data-"+b.replace(Nb,"-$&").toLowerCase(),"string"==typeof(c=a.getAttribute(d))){try{d=c,c="true"===d||"false"!==d&&("null"===d?null:d===+d+""?+d:Ob.test(d)?JSON.parse(d):d)}catch(e){}K.set(a,b,c)}else c=void 0;return c}function Ya(a,b,c,f){var e,g,k=20,l=f?function(){return f.cur()}:function(){return d.css(a,b,"")},t=l(),I=c&&c[3]||(d.cssNumber[b]?"":"px"),p=(d.cssNumber[b]||"px"!==I&&+t)&&za.exec(d.css(a,b));if(p&&p[3]!==
I){t/=2;I=I||p[3];for(p=+t||1;k--;)d.style(a,b,p+I),0>=(1-g)*(1-(g=l()/t||.5))&&(k=0),p/=g;p*=2;d.style(a,b,p+I);c=c||[]}return c&&(p=+p||+t||0,e=c[1]?p+(c[1]+1)*c[2]:+c[2],f&&(f.unit=I,f.start=p,f.end=e)),e}function ra(a,b){for(var c,f,e=[],g=0,k=a.length;g<k;g++)if((f=a[g]).style)if(c=f.style.display,b){if("none"===c&&(e[g]=C.get(f,"display")||null,e[g]||(f.style.display="")),""===f.style.display&&Ca(f)){c=g;var l=void 0;var t=f.ownerDocument;var I=f.nodeName;t=(f=Za[I])||(l=t.body.appendChild(t.createElement(I)),
f=d.css(l,"display"),l.parentNode.removeChild(l),"none"===f&&(f="block"),Za[I]=f,f);e[c]=t}}else"none"!==c&&(e[g]="none",C.set(f,"display",c));for(g=0;g<k;g++)null!=e[g]&&(a[g].style.display=e[g]);return a}function U(a,b){var c;return c="undefined"!=typeof a.getElementsByTagName?a.getElementsByTagName(b||"*"):"undefined"!=typeof a.querySelectorAll?a.querySelectorAll(b||"*"):[],void 0===b||b&&x(a,b)?d.merge([a],c):c}function Ja(a,b){for(var c=0,d=a.length;c<d;c++)C.set(a[c],"globalEval",!b||C.get(b[c],
"globalEval"))}function $a(a,b,c,f,e){for(var g,k,l,t,I=b.createDocumentFragment(),p=[],m=0,h=a.length;m<h;m++)if((g=a[m])||0===g)if("object"===z(g))d.merge(p,g.nodeType?[g]:g);else if(Qb.test(g)){k=k||I.appendChild(b.createElement("div"));l=(ab.exec(g)||["",""])[1].toLowerCase();l=V[l]||V._default;k.innerHTML=l[1]+d.htmlPrefilter(g)+l[2];for(l=l[0];l--;)k=k.lastChild;d.merge(p,k.childNodes);(k=I.firstChild).textContent=""}else p.push(b.createTextNode(g));I.textContent="";for(m=0;g=p[m++];)if(f&&
-1<d.inArray(g,f))e&&e.push(g);else if(t=d.contains(g.ownerDocument,g),k=U(I.appendChild(g),"script"),t&&Ja(k),c)for(l=0;g=k[l++];)bb.test(g.type||"")&&c.push(g);return I}function Da(){return!0}function sa(){return!1}function cb(){try{return B.activeElement}catch(a){}}function Ka(a,b,c,f,e,g){var k,l;if("object"==typeof b){"string"!=typeof c&&(f=f||c,c=void 0);for(l in b)Ka(a,l,c,f,b[l],g);return a}if(null==f&&null==e?(e=c,f=c=void 0):null==e&&("string"==typeof c?(e=f,f=void 0):(e=f,f=c,c=void 0)),
!1===e)e=sa;else if(!e)return a;return 1===g&&(k=e,(e=function(a){return d().off(a),k.apply(this,arguments)}).guid=k.guid||(k.guid=d.guid++)),a.each(function(){d.event.add(this,b,e,f,c)})}function db(a,b){return x(a,"table")&&x(11!==b.nodeType?b:b.firstChild,"tr")?d(a).children("tbody")[0]||a:a}function Rb(a){return a.type=(null!==a.getAttribute("type"))+"/"+a.type,a}function Sb(a){return"true/"===(a.type||"").slice(0,5)?a.type=a.type.slice(5):a.removeAttribute("type"),a}function eb(a,b){var c,f,
e,g,k,l;if(1===b.nodeType){if(C.hasData(a)&&(c=C.access(a),f=C.set(b,c),l=c.events))for(e in delete f.handle,f.events={},l)for(c=0,f=l[e].length;c<f;c++)d.event.add(b,e,l[e][c]);K.hasData(a)&&(g=K.access(a),k=d.extend({},g),K.set(b,k))}}function ta(a,b,c,f){b=fb.apply([],b);var e,g,k,l=0,t=a.length,I=t-1,p=b[0],m=A(p);if(m||1<t&&"string"==typeof p&&!H.checkClone&&Tb.test(p))return a.each(function(d){var e=a.eq(d);m&&(b[0]=p.call(this,d,e.html()));ta(e,b,c,f)});if(t&&(e=$a(b,a[0].ownerDocument,!1,
a,f),g=e.firstChild,1===e.childNodes.length&&(e=g),g||f)){for(k=(g=d.map(U(e,"script"),Rb)).length;l<t;l++){var h=e;l!==I&&(h=d.clone(h,!0,!0),k&&d.merge(g,U(h,"script")));c.call(a[l],h,l)}if(k)for(e=g[g.length-1].ownerDocument,d.map(g,Sb),l=0;l<k;l++)h=g[l],bb.test(h.type||"")&&!C.access(h,"globalEval")&&d.contains(e,h)&&(h.src&&"module"!==(h.type||"").toLowerCase()?d._evalUrl&&d._evalUrl(h.src):J(h.textContent.replace(Ub,""),e,h))}return a}function gb(a,b,c){for(var f=b?d.filter(b,a):a,e=0;null!=
(b=f[e]);e++)c||1!==b.nodeType||d.cleanData(U(b)),b.parentNode&&(c&&d.contains(b.ownerDocument,b)&&Ja(U(b,"script")),b.parentNode.removeChild(b));return a}function ca(a,b,c){var f,e,g,k,l=a.style;return(c=c||ua(a))&&(""!==(k=c.getPropertyValue(b)||c[b])||d.contains(a.ownerDocument,a)||(k=d.style(a,b)),!H.pixelBoxStyles()&&La.test(k)&&Vb.test(b)&&(f=l.width,e=l.minWidth,g=l.maxWidth,l.minWidth=l.maxWidth=l.width=k,k=c.width,l.width=f,l.minWidth=e,l.maxWidth=g)),void 0!==k?k+"":k}function hb(a,b){return{get:function(){if(!a())return(this.get=
b).apply(this,arguments);delete this.get}}}function ib(a){var b=d.cssProps[a];if(!b){b=d.cssProps;a:{var c=a;if(!(c in jb)){for(var f=c[0].toUpperCase()+c.slice(1),e=kb.length;e--;)if((c=kb[e]+f)in jb)break a;c=void 0}}b=b[a]=c||a}return b}function lb(a,b,c){return(a=za.exec(b))?Math.max(0,a[2]-(c||0))+(a[3]||"px"):b}function Ma(a,b,c,f,e,g){var k="width"===b?1:0,l=0,t=0;if(c===(f?"border":"content"))return 0;for(;4>k;k+=2)"margin"===c&&(t+=d.css(a,c+da[k],!0,e)),f?("content"===c&&(t-=d.css(a,"padding"+
da[k],!0,e)),"margin"!==c&&(t-=d.css(a,"border"+da[k]+"Width",!0,e))):(t+=d.css(a,"padding"+da[k],!0,e),"padding"!==c?t+=d.css(a,"border"+da[k]+"Width",!0,e):l+=d.css(a,"border"+da[k]+"Width",!0,e));return!f&&0<=g&&(t+=Math.max(0,Math.ceil(a["offset"+b[0].toUpperCase()+b.slice(1)]-g-t-l-.5))),t}function mb(a,b,c){var f=ua(a),e=ca(a,b,f),g="border-box"===d.css(a,"boxSizing",!1,f),k=g;if(La.test(e)){if(!c)return e;e="auto"}return k=k&&(H.boxSizingReliable()||e===a.style[b]),("auto"===e||!parseFloat(e)&&
"inline"===d.css(a,"display",!1,f))&&(e=a["offset"+b[0].toUpperCase()+b.slice(1)],k=!0),(e=parseFloat(e)||0)+Ma(a,b,c||(g?"border":"content"),k,f,e)+"px"}function R(a,b,c,d,e){return new R.prototype.init(a,b,c,d,e)}function Na(){ka&&(!1===B.hidden&&u.requestAnimationFrame?u.requestAnimationFrame(Na):u.setTimeout(Na,d.fx.interval),d.fx.tick())}function nb(){return u.setTimeout(function(){ea=void 0}),ea=Date.now()}function Fa(a,b){var c,d=0,e={height:a};for(b=b?1:0;4>d;d+=2-b)e["margin"+(c=da[d])]=
e["padding"+c]=a;return b&&(e.opacity=e.width=a),e}function ob(a,b,c){for(var d,e=(Y.tweeners[b]||[]).concat(Y.tweeners["*"]),g=0,k=e.length;g<k;g++)if(d=e[g].call(c,b,a))return d}function Wb(a,b){var c,f,e,g,k;for(c in a)if(f=n(c),e=b[f],g=a[c],Array.isArray(g)&&(e=g[1],g=a[c]=g[0]),c!==f&&(a[f]=g,delete a[c]),(k=d.cssHooks[f])&&"expand"in k)for(c in g=k.expand(g),delete a[f],g)c in a||(a[c]=g[c],b[c]=e);else b[f]=e}function Y(a,b,c){var f,e=0,g=Y.prefilters.length,k=d.Deferred().always(function(){delete l.elem}),
l=function(){if(f)return!1;var b=ea||nb();b=Math.max(0,t.startTime+t.duration-b);for(var c=1-(b/t.duration||0),d=0,e=t.tweens.length;d<e;d++)t.tweens[d].run(c);return k.notifyWith(a,[t,c,b]),1>c&&e?b:(e||k.notifyWith(a,[t,1,0]),k.resolveWith(a,[t]),!1)},t=k.promise({elem:a,props:d.extend({},b),opts:d.extend(!0,{specialEasing:{},easing:d.easing._default},c),originalProperties:b,originalOptions:c,startTime:ea||nb(),duration:c.duration,tweens:[],createTween:function(b,c){b=d.Tween(a,t.opts,b,c,t.opts.specialEasing[b]||
t.opts.easing);return t.tweens.push(b),b},stop:function(b){var c=0,d=b?t.tweens.length:0;if(f)return this;for(f=!0;c<d;c++)t.tweens[c].run(1);return b?(k.notifyWith(a,[t,1,0]),k.resolveWith(a,[t,b])):k.rejectWith(a,[t,b]),this}});c=t.props;for(Wb(c,t.opts.specialEasing);e<g;e++)if(b=Y.prefilters[e].call(t,a,c,t.opts))return A(b.stop)&&(d._queueHooks(t.elem,t.opts.queue).stop=b.stop.bind(b)),b;return d.map(c,ob,t),A(t.opts.start)&&t.opts.start.call(a,t),t.progress(t.opts.progress).done(t.opts.done,
t.opts.complete).fail(t.opts.fail).always(t.opts.always),d.fx.timer(d.extend(l,{elem:a,anim:t,queue:t.opts.queue})),t}function ja(a){return(a.match(N)||[]).join(" ")}function X(a){return a.getAttribute&&a.getAttribute("class")||""}function Oa(a){return Array.isArray(a)?a:"string"==typeof a?a.match(N)||[]:[]}function Pa(a,b,c,f){var e;if(Array.isArray(b))d.each(b,function(b,d){c||Xb.test(a)?f(a,d):Pa(a+"["+("object"==typeof d&&null!=d?b:"")+"]",d,c,f)});else if(c||"object"!==z(b))f(a,b);else for(e in b)Pa(a+
"["+e+"]",b[e],c,f)}function pb(a){return function(b,c){"string"!=typeof b&&(c=b,b="*");var d=0,e=b.toLowerCase().match(N)||[];if(A(c))for(;b=e[d++];)"+"===b[0]?(b=b.slice(1)||"*",(a[b]=a[b]||[]).unshift(c)):(a[b]=a[b]||[]).push(c)}}function qb(a,b,c,f){function e(l){var t;return g[l]=!0,d.each(a[l]||[],function(a,d){a=d(b,c,f);return"string"!=typeof a||k||g[a]?k?!(t=a):void 0:(b.dataTypes.unshift(a),e(a),!1)}),t}var g={},k=a===Qa;return e(b.dataTypes[0])||!g["*"]&&e("*")}function Ra(a,b){var c,f,
e=d.ajaxSettings.flatOptions||{};for(c in b)void 0!==b[c]&&((e[c]?a:f||(f={}))[c]=b[c]);return f&&d.extend(!0,a,f),a}var la=[],B=u.document,Yb=Object.getPrototypeOf,aa=la.slice,fb=la.concat,Sa=la.push,ya=la.indexOf,xa={},Xa=xa.toString,Ga=xa.hasOwnProperty,rb=Ga.toString,Zb=rb.call(Object),H={},A=function(a){return"function"==typeof a&&"number"!=typeof a.nodeType},qa=function(a){return null!=a&&a===a.window},Kb={type:!0,src:!0,noModule:!0},d=function(a,b){return new d.fn.init(a,b)},$b=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;
d.fn=d.prototype={jquery:"3.3.1",constructor:d,length:0,toArray:function(){return aa.call(this)},get:function(a){return null==a?aa.call(this):0>a?this[a+this.length]:this[a]},pushStack:function(a){a=d.merge(this.constructor(),a);return a.prevObject=this,a},each:function(a){return d.each(this,a)},map:function(a){return this.pushStack(d.map(this,function(b,c){return a.call(b,c,b)}))},slice:function(){return this.pushStack(aa.apply(this,arguments))},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},
eq:function(a){var b=this.length;a=+a+(0>a?b:0);return this.pushStack(0<=a&&a<b?[this[a]]:[])},end:function(){return this.prevObject||this.constructor()},push:Sa,sort:la.sort,splice:la.splice};d.extend=d.fn.extend=function(){var a,b,c,f,e,g=arguments[0]||{},k=1,l=arguments.length,t=!1;"boolean"==typeof g&&(t=g,g=arguments[k]||{},k++);"object"==typeof g||A(g)||(g={});for(k===l&&(g=this,k--);k<l;k++)if(null!=(a=arguments[k]))for(b in a){var h=g[b];g!==(c=a[b])&&(t&&c&&(d.isPlainObject(c)||(f=Array.isArray(c)))?
(f?(f=!1,e=h&&Array.isArray(h)?h:[]):e=h&&d.isPlainObject(h)?h:{},g[b]=d.extend(t,e,c)):void 0!==c&&(g[b]=c))}return g};d.extend({expando:"jQuery"+("3.3.1"+Math.random()).replace(/\D/g,""),isReady:!0,error:function(a){throw Error(a);},noop:function(){},isPlainObject:function(a){var b,c;return!(!a||"[object Object]"!==Xa.call(a))&&(!(b=Yb(a))||"function"==typeof(c=Ga.call(b,"constructor")&&b.constructor)&&rb.call(c)===Zb)},isEmptyObject:function(a){for(var b in a)return!1;return!0},globalEval:function(a){J(a)},
each:function(a,b){var c,d=0;if(y(a))for(c=a.length;d<c&&!1!==b.call(a[d],d,a[d]);d++);else for(d in a)if(!1===b.call(a[d],d,a[d]))break;return a},trim:function(a){return null==a?"":(a+"").replace($b,"")},makeArray:function(a,b){b=b||[];return null!=a&&(y(Object(a))?d.merge(b,"string"==typeof a?[a]:a):Sa.call(b,a)),b},inArray:function(a,b,c){return null==b?-1:ya.call(b,a,c)},merge:function(a,b){for(var c=+b.length,d=0,e=a.length;d<c;d++)a[e++]=b[d];return a.length=e,a},grep:function(a,b,c){var d=
[],e=0,g=a.length;for(c=!c;e<g;e++)!b(a[e],e)!==c&&d.push(a[e]);return d},map:function(a,b,c){var d,e,g=0,k=[];if(y(a))for(d=a.length;g<d;g++)null!=(e=b(a[g],g,c))&&k.push(e);else for(g in a)null!=(e=b(a[g],g,c))&&k.push(e);return fb.apply([],k)},guid:1,support:H});"function"==typeof Symbol&&(d.fn[Symbol.iterator]=la[Symbol.iterator]);d.each("Boolean Number String Function Array Date RegExp Object Error Symbol".split(" "),function(a,b){xa["[object "+b+"]"]=b.toLowerCase()});var oa=function(a){function b(a,
b,c,d){var e,f,g,D,k=b&&b.ownerDocument,l=b?b.nodeType:9;if(c=c||[],"string"!=typeof a||!a||1!==l&&9!==l&&11!==l)return c;if(!d&&((b?b.ownerDocument||b:ba)!==L&&Aa(b),b=b||L,x)){if(11!==l&&(D=Ba.exec(a)))if(e=D[1])if(9===l){if(!(f=b.getElementById(e)))return c;if(f.id===e)return c.push(f),c}else{if(k&&(f=k.getElementById(e))&&M(b,f)&&f.id===e)return c.push(f),c}else{if(D[2])return Q.apply(c,b.getElementsByTagName(a)),c;if((e=D[3])&&P.getElementsByClassName&&b.getElementsByClassName)return Q.apply(c,
b.getElementsByClassName(e)),c}if(!(!P.qsa||ia[a+" "]||T&&T.test(a))){if(1!==l){k=b;var W=a}else if("object"!==b.nodeName.toLowerCase()){(g=b.getAttribute("id"))?g=g.replace(wa,xa):b.setAttribute("id",g=O);for(e=(f=ka(a)).length;e--;)f[e]="#"+g+" "+n(f[e]);W=f.join(",");k=pa.test(a)&&m(b.parentNode)||b}if(W)try{return Q.apply(c,k.querySelectorAll(W)),c}catch(Ec){}finally{g===O&&b.removeAttribute("id")}}}return J(a.replace(aa,"$1"),b,c,d)}function c(){function a(c,d){return b.push(c+" ")>G.cacheLength&&
delete a[b.shift()],a[c+" "]=d}var b=[];return a}function d(a){return a[O]=!0,a}function e(a){var b=L.createElement("fieldset");try{return!!a(b)}catch(S){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}}function g(a,b){a=a.split("|");for(var c=a.length;c--;)G.attrHandle[a[c]]=b}function k(a,b){var c=b&&a,d=c&&1===a.nodeType&&1===b.nodeType&&a.sourceIndex-b.sourceIndex;if(d)return d;if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1}function l(a){return function(b){return"input"===
b.nodeName.toLowerCase()&&b.type===a}}function t(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function h(a){return function(b){return"form"in b?b.parentNode&&!1===b.disabled?"label"in b?"label"in b.parentNode?b.parentNode.disabled===a:b.disabled===a:b.isDisabled===a||b.isDisabled!==!a&&Ca(b)===a:b.disabled===a:"label"in b&&b.disabled===a}}function p(a){return d(function(b){return b=+b,d(function(c,d){for(var e,f=a([],c.length,b),g=f.length;g--;)c[e=
f[g]]&&(c[e]=!(d[e]=c[e]))})})}function m(a){return a&&"undefined"!=typeof a.getElementsByTagName&&a}function q(){}function n(a){for(var b=0,c=a.length,d="";b<c;b++)d+=a[b].value;return d}function r(a,b,c){var d=b.dir,e=b.next,f=e||d,g=c&&"parentNode"===f,k=U++;return b.first?function(b,c,e){for(;b=b[d];)if(1===b.nodeType||g)return a(b,c,e);return!1}:function(b,c,D){var l,t,W,p=[K,k];if(D)for(;b=b[d];){if((1===b.nodeType||g)&&a(b,c,D))return!0}else for(;b=b[d];)if(1===b.nodeType||g)if(W=b[O]||(b[O]=
{}),t=W[b.uniqueID]||(W[b.uniqueID]={}),e&&e===b.nodeName.toLowerCase())b=b[d]||b;else{if((l=t[f])&&l[0]===K&&l[1]===k)return p[2]=l[2];if(t[f]=p,p[2]=a(b,c,D))return!0}return!1}}function v(a){return 1<a.length?function(b,c,d){for(var e=a.length;e--;)if(!a[e](b,c,d))return!1;return!0}:a[0]}function u(a,b,c,d,e){for(var f,g=[],k=0,D=a.length,l=null!=b;k<D;k++)(f=a[k])&&(c&&!c(f,d,e)||(g.push(f),l&&b.push(k)));return g}function C(a,c,e,f,g,k){return f&&!f[O]&&(f=C(f)),g&&!g[O]&&(g=C(g,k)),d(function(d,
k,D,l){var t,W=[],p=[],fa=k.length,S;if(!(S=d)){S=c||"*";for(var h=D.nodeType?[D]:D,m=[],I=0,Ea=h.length;I<Ea;I++)b(S,h[I],m);S=m}S=!a||!d&&c?S:u(S,W,a,D,l);h=e?g||(d?a:fa||f)?[]:k:S;if(e&&e(S,h,D,l),f){var q=u(h,p);f(q,[],D,l);for(D=q.length;D--;)(t=q[D])&&(h[p[D]]=!(S[p[D]]=t))}if(d){if(g||a){if(g){q=[];for(D=h.length;D--;)(t=h[D])&&q.push(S[D]=t);g(null,h=[],q,l)}for(D=h.length;D--;)(t=h[D])&&-1<(q=g?X(d,t):W[D])&&(d[q]=!(k[q]=t))}}else h=u(h===k?h.splice(fa,h.length):h),g?g(null,k,h,l):Q.apply(k,
h)})}function A(a){var b,c,d=a.length,e=G.relative[a[0].type];var f=e||G.relative[" "];for(var g=e?1:0,k=r(function(a){return a===b},f,!0),D=r(function(a){return-1<X(b,a)},f,!0),l=[function(a,c,d){a=!e&&(d||c!==z)||((b=c).nodeType?k(a,c,d):D(a,c,d));return b=null,a}];g<d;g++)if(f=G.relative[a[g].type])l=[r(v(l),f)];else{if((f=G.filter[a[g].type].apply(null,a[g].matches))[O]){for(c=++g;c<d&&!G.relative[a[c].type];c++);return C(1<g&&v(l),1<g&&n(a.slice(0,g-1).concat({value:" "===a[g-2].type?"*":""})).replace(aa,
"$1"),f,g<c&&A(a.slice(g,c)),c<d&&A(a=a.slice(c)),c<d&&n(a))}l.push(f)}return v(l)}function ac(a,c){var e=0<c.length,f=0<a.length,g=function(d,g,k,D,l){var t,p,W=0,h="0",S=d&&[],fa=[],m=z,q=d||f&&G.find.TAG("*",l),I=K+=null==m?1:Math.random()||.1,n=q.length;for(l&&(z=g===L||g||l);h!==n&&null!=(t=q[h]);h++){if(f&&t){var Ea=0;for(g||t.ownerDocument===L||(Aa(t),k=!x);p=a[Ea++];)if(p(t,g||L,k)){D.push(t);break}l&&(K=I)}e&&((t=!p&&t)&&W--,d&&S.push(t))}if(W+=h,e&&h!==W){for(Ea=0;p=c[Ea++];)p(S,fa,g,k);
if(d){if(0<W)for(;h--;)S[h]||fa[h]||(fa[h]=da.call(D));fa=u(fa)}Q.apply(D,fa);l&&!d&&0<fa.length&&1<W+c.length&&b.uniqueSort(D)}return l&&(K=I,z=m),S};return e?d(g):g}var w,G,Z,J,z,B,E,L,y,x,T,F,H,M,O="sizzle"+1*new Date,ba=a.document,K=0,U=0,tb=c(),R=c(),ia=c(),V=function(a,b){return a===b&&(E=!0),0},Y={}.hasOwnProperty,N=[],da=N.pop,ha=N.push,Q=N.push,ja=N.slice,X=function(a,b){for(var c=0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1},la=/[\x20\t\r\n\f]+/g,aa=/^[\x20\t\r\n\f]+|((?:^|[^\\])(?:\\.)*)[\x20\t\r\n\f]+$/g,
oa=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,qa=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,ra=/=[\x20\t\r\n\f]*([^\]'"]*?)[\x20\t\r\n\f]*\]/g,sa=/:((?:\\.|[\w-]|[^\x00-\xa0])+)(?:\((('((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)")|((?:\\.|[^\\()[\]]|\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\])*)|.*)\)|)/,ta=/^(?:\\.|[\w-]|[^\x00-\xa0])+$/,ea={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,
CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:/^((?:\\.|[\w-]|[^\x00-\xa0])+|[*])/,ATTR:/^\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\]/,PSEUDO:/^:((?:\\.|[\w-]|[^\x00-\xa0])+)(?:\((('((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)")|((?:\\.|[^\\()[\]]|\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\])*)|.*)\)|)/,
CHILD:/^:(only|first|last|nth|nth-last)-(child|of-type)(?:\([\x20\t\r\n\f]*(even|odd|(([+-]|)(\d*)n|)[\x20\t\r\n\f]*(?:([+-]|)[\x20\t\r\n\f]*(\d+)|))[\x20\t\r\n\f]*\)|)/i,bool:/^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$/i,needsContext:/^[\x20\t\r\n\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\([\x20\t\r\n\f]*((?:-\d)?\d*)[\x20\t\r\n\f]*\)|)(?=[^-]|$)/i},va=/^(?:input|select|textarea|button)$/i,za=/^h\d$/i,ca=
/^[^{]+\{\s*\[native \w/,Ba=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,pa=/[+~]/,ma=/\\([\da-f]{1,6}[\x20\t\r\n\f]?|([\x20\t\r\n\f])|.)/ig,na=function(a,b,c){a="0x"+b-65536;return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,1023&a|56320)},wa=/([\0-\x1f\x7f]|^-?\d)|^-$|[^\0-\x1f\x7f-\uFFFF\w-]/g,xa=function(a,b){return b?"\x00"===a?"\ufffd":a.slice(0,-1)+"\\"+a.charCodeAt(a.length-1).toString(16)+" ":"\\"+a},ya=function(){Aa()},Ca=r(function(a){return!0===a.disabled&&("form"in
a||"label"in a)},{dir:"parentNode",next:"legend"});try{Q.apply(N=ja.call(ba.childNodes),ba.childNodes),N[ba.childNodes.length].nodeType}catch(D){Q={apply:N.length?function(a,b){ha.apply(a,ja.call(b))}:function(a,b){for(var c=a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}var P=b.support={};var Da=b.isXML=function(a){a=a&&(a.ownerDocument||a).documentElement;return!!a&&"HTML"!==a.nodeName};var Aa=b.setDocument=function(a){var b,c;a=a?a.ownerDocument||a:ba;return a!==L&&9===a.nodeType&&a.documentElement?
(L=a,y=L.documentElement,x=!Da(L),ba!==L&&(c=L.defaultView)&&c.top!==c&&(c.addEventListener?c.addEventListener("unload",ya,!1):c.attachEvent&&c.attachEvent("onunload",ya)),P.attributes=e(function(a){return a.className="i",!a.getAttribute("className")}),P.getElementsByTagName=e(function(a){return a.appendChild(L.createComment("")),!a.getElementsByTagName("*").length}),P.getElementsByClassName=ca.test(L.getElementsByClassName),P.getById=e(function(a){return y.appendChild(a).id=O,!L.getElementsByName||
!L.getElementsByName(O).length}),P.getById?(G.filter.ID=function(a){var b=a.replace(ma,na);return function(a){return a.getAttribute("id")===b}},G.find.ID=function(a,b){if("undefined"!=typeof b.getElementById&&x)return(a=b.getElementById(a))?[a]:[]}):(G.filter.ID=function(a){var b=a.replace(ma,na);return function(a){return(a="undefined"!=typeof a.getAttributeNode&&a.getAttributeNode("id"))&&a.value===b}},G.find.ID=function(a,b){if("undefined"!=typeof b.getElementById&&x){var c,d=b.getElementById(a);
if(d){if((c=d.getAttributeNode("id"))&&c.value===a)return[d];var e=b.getElementsByName(a);for(b=0;d=e[b++];)if((c=d.getAttributeNode("id"))&&c.value===a)return[d]}return[]}}),G.find.TAG=P.getElementsByTagName?function(a,b){return"undefined"!=typeof b.getElementsByTagName?b.getElementsByTagName(a):P.qsa?b.querySelectorAll(a):void 0}:function(a,b){var c=[],d=0;b=b.getElementsByTagName(a);if("*"===a){for(;a=b[d++];)1===a.nodeType&&c.push(a);return c}return b},G.find.CLASS=P.getElementsByClassName&&function(a,
b){if("undefined"!=typeof b.getElementsByClassName&&x)return b.getElementsByClassName(a)},F=[],T=[],(P.qsa=ca.test(L.querySelectorAll))&&(e(function(a){y.appendChild(a).innerHTML="<a id='"+O+"'></a><select id='"+O+"-\r\\' msallowcapture=''><option selected=''></option></select>";a.querySelectorAll("[msallowcapture^='']").length&&T.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||T.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");
a.querySelectorAll("[id~="+O+"-]").length||T.push("~=");a.querySelectorAll(":checked").length||T.push(":checked");a.querySelectorAll("a#"+O+"+*").length||T.push(".#.+[+~]")}),e(function(a){a.innerHTML="<a href='' disabled='disabled'></a><select disabled='disabled'><option/></select>";var b=L.createElement("input");b.setAttribute("type","hidden");a.appendChild(b).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&T.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");2!==a.querySelectorAll(":enabled").length&&
T.push(":enabled",":disabled");y.appendChild(a).disabled=!0;2!==a.querySelectorAll(":disabled").length&&T.push(":enabled",":disabled");a.querySelectorAll("*,:x");T.push(",.*:")})),(P.matchesSelector=ca.test(H=y.matches||y.webkitMatchesSelector||y.mozMatchesSelector||y.oMatchesSelector||y.msMatchesSelector))&&e(function(a){P.disconnectedMatch=H.call(a,"*");H.call(a,"[s!='']:x");F.push("!=",":((?:\\\\.|[\\w-]|[^\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)")}),
T=T.length&&new RegExp(T.join("|")),F=F.length&&new RegExp(F.join("|")),b=ca.test(y.compareDocumentPosition),M=b||ca.test(y.contains)?function(a,b){var c=9===a.nodeType?a.documentElement:a;b=b&&b.parentNode;return a===b||!(!b||1!==b.nodeType||!(c.contains?c.contains(b):a.compareDocumentPosition&&16&a.compareDocumentPosition(b)))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1},V=b?function(a,b){if(a===b)return E=!0,0;var c=!a.compareDocumentPosition-!b.compareDocumentPosition;
return c||(1&(c=(a.ownerDocument||a)===(b.ownerDocument||b)?a.compareDocumentPosition(b):1)||!P.sortDetached&&b.compareDocumentPosition(a)===c?a===L||a.ownerDocument===ba&&M(ba,a)?-1:b===L||b.ownerDocument===ba&&M(ba,b)?1:B?X(B,a)-X(B,b):0:4&c?-1:1)}:function(a,b){if(a===b)return E=!0,0;var c=0,d=a.parentNode,e=b.parentNode,f=[a],g=[b];if(!d||!e)return a===L?-1:b===L?1:d?-1:e?1:B?X(B,a)-X(B,b):0;if(d===e)return k(a,b);for(;a=a.parentNode;)f.unshift(a);for(a=b;a=a.parentNode;)g.unshift(a);for(;f[c]===
g[c];)c++;return c?k(f[c],g[c]):f[c]===ba?-1:g[c]===ba?1:0},L):L};b.matches=function(a,c){return b(a,null,null,c)};b.matchesSelector=function(a,c){if((a.ownerDocument||a)!==L&&Aa(a),c=c.replace(ra,"='$1']"),!(!P.matchesSelector||!x||ia[c+" "]||F&&F.test(c)||T&&T.test(c)))try{var d=H.call(a,c);if(d||P.disconnectedMatch||a.document&&11!==a.document.nodeType)return d}catch(fa){}return 0<b(c,L,null,[a]).length};b.contains=function(a,b){return(a.ownerDocument||a)!==L&&Aa(a),M(a,b)};b.attr=function(a,b){(a.ownerDocument||
a)!==L&&Aa(a);var c=G.attrHandle[b.toLowerCase()];c=c&&Y.call(G.attrHandle,b.toLowerCase())?c(a,b,!x):void 0;return void 0!==c?c:P.attributes||!x?a.getAttribute(b):(c=a.getAttributeNode(b))&&c.specified?c.value:null};b.escape=function(a){return(a+"").replace(wa,xa)};b.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};b.uniqueSort=function(a){var b,c=[],d=0,e=0;if(E=!P.detectDuplicates,B=!P.sortStable&&a.slice(0),a.sort(V),E){for(;b=a[e++];)b===a[e]&&(d=c.push(e));for(;d--;)a.splice(c[d],
1)}return B=null,a};var ua=b.getText=function(a){var b,c="",d=0;if(b=a.nodeType)if(1===b||9===b||11===b){if("string"==typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)c+=ua(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=a[d++];)c+=ua(b);return c};(G=b.selectors={cacheLength:50,createPseudo:d,match:ea,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){return a[1]=
a[1].replace(ma,na),a[3]=(a[3]||a[4]||a[5]||"").replace(ma,na),"~="===a[2]&&(a[3]=" "+a[3]+" "),a.slice(0,4)},CHILD:function(a){return a[1]=a[1].toLowerCase(),"nth"===a[1].slice(0,3)?(a[3]||b.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&b.error(a[0]),a},PSEUDO:function(a){var b,c=!a[6]&&a[2];return ea.CHILD.test(a[0])?null:(a[3]?a[2]=a[4]||a[5]||"":c&&sa.test(c)&&(b=ka(c,!0))&&(b=c.indexOf(")",c.length-b)-c.length)&&(a[0]=a[0].slice(0,
b),a[2]=c.slice(0,b)),a.slice(0,3))}},filter:{TAG:function(a){var b=a.replace(ma,na).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=tb[a+" "];return b||(b=new RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"),tb(a,function(a){return b.test("string"==typeof a.className&&a.className||"undefined"!=typeof a.getAttribute&&a.getAttribute("class")||"")}))},ATTR:function(a,c,d){return function(e){e=b.attr(e,
a);return null==e?"!="===c:!c||(e+="","="===c?e===d:"!="===c?e!==d:"^="===c?d&&0===e.indexOf(d):"*="===c?d&&-1<e.indexOf(d):"$="===c?d&&e.slice(-d.length)===d:"~="===c?-1<(" "+e.replace(la," ")+" ").indexOf(d):"|="===c&&(e===d||e.slice(0,d.length+1)===d+"-"))}},CHILD:function(a,b,c,d,e){var f="nth"!==a.slice(0,3),g="last"!==a.slice(-4),k="of-type"===b;return 1===d&&0===e?function(a){return!!a.parentNode}:function(b,c,l){var t,p,h,D;c=f!==g?"nextSibling":"previousSibling";var m=b.parentNode,q=k&&b.nodeName.toLowerCase(),
I=!l&&!k,n=!1;if(m){if(f){for(;c;){for(h=b;h=h[c];)if(k?h.nodeName.toLowerCase()===q:1===h.nodeType)return!1;var r=c="only"===a&&!r&&"nextSibling"}return!0}if(r=[g?m.firstChild:m.lastChild],g&&I)for(n=(D=(t=(l=(p=(h=m)[O]||(h[O]={}))[h.uniqueID]||(p[h.uniqueID]={}))[a]||[])[0]===K&&t[1])&&t[2],h=D&&m.childNodes[D];h=++D&&h&&h[c]||(n=D=0)||r.pop();){if(1===h.nodeType&&++n&&h===b){l[a]=[K,D,n];break}}else if(I&&(n=D=(t=((p=(h=b)[O]||(h[O]={}))[h.uniqueID]||(p[h.uniqueID]={}))[a]||[])[0]===K&&t[1]),
!1===n)for(;(h=++D&&h&&h[c]||(n=D=0)||r.pop())&&((k?h.nodeName.toLowerCase()!==q:1!==h.nodeType)||!++n||(I&&((l=(p=h[O]||(h[O]={}))[h.uniqueID]||(p[h.uniqueID]={}))[a]=[K,n]),h!==b)););return(n-=e)===d||0==n%d&&0<=n/d}}},PSEUDO:function(a,c){var e,f=G.pseudos[a]||G.setFilters[a.toLowerCase()]||b.error("unsupported pseudo: "+a);return f[O]?f(c):1<f.length?(e=[a,a,"",c],G.setFilters.hasOwnProperty(a.toLowerCase())?d(function(a,b){for(var d,e=f(a,c),g=e.length;g--;)a[d=X(a,e[g])]=!(b[d]=e[g])}):function(a){return f(a,
0,e)}):f}},pseudos:{not:d(function(a){var b=[],c=[],e=Z(a.replace(aa,"$1"));return e[O]?d(function(a,b,c,d){var f;c=e(a,null,d,[]);for(d=a.length;d--;)(f=c[d])&&(a[d]=!(b[d]=f))}):function(a,d,f){return b[0]=a,e(b,null,f,c),b[0]=null,!c.pop()}}),has:d(function(a){return function(c){return 0<b(a,c).length}}),contains:d(function(a){return a=a.replace(ma,na),function(b){return-1<(b.textContent||b.innerText||ua(b)).indexOf(a)}}),lang:d(function(a){return ta.test(a||"")||b.error("unsupported lang: "+a),
a=a.replace(ma,na).toLowerCase(),function(b){var c;do if(c=x?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return(c=c.toLowerCase())===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&1===b.nodeType);return!1}}),target:function(b){var c=a.location&&a.location.hash;return c&&c.slice(1)===b.id},root:function(a){return a===y},focus:function(a){return a===L.activeElement&&(!L.hasFocus||L.hasFocus())&&!!(a.type||a.href||~a.tabIndex)},enabled:h(!1),disabled:h(!0),checked:function(a){var b=a.nodeName.toLowerCase();
return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){return a.parentNode&&a.parentNode.selectedIndex,!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!G.pseudos.empty(a)},header:function(a){return za.test(a.nodeName)},input:function(a){return va.test(a.nodeName)},button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===
a.nodeName.toLowerCase()&&"text"===a.type&&(null==(b=a.getAttribute("type"))||"text"===b.toLowerCase())},first:p(function(){return[0]}),last:p(function(a,b){return[b-1]}),eq:p(function(a,b,c){return[0>c?c+b:c]}),even:p(function(a,b){for(var c=0;c<b;c+=2)a.push(c);return a}),odd:p(function(a,b){for(var c=1;c<b;c+=2)a.push(c);return a}),lt:p(function(a,b,c){for(b=0>c?c+b:c;0<=--b;)a.push(b);return a}),gt:p(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}}).pseudos.nth=G.pseudos.eq;for(w in{radio:!0,
checkbox:!0,file:!0,password:!0,image:!0})G.pseudos[w]=l(w);for(w in{submit:!0,reset:!0})G.pseudos[w]=t(w);q.prototype=G.filters=G.pseudos;G.setFilters=new q;var ka=b.tokenize=function(a,c){var d,e,f,g,k;if(g=R[a+" "])return c?0:g.slice(0);g=a;var l=[];for(k=G.preFilter;g;){t&&!(d=oa.exec(g))||(d&&(g=g.slice(d[0].length)||g),l.push(e=[]));var t=!1;(d=qa.exec(g))&&(t=d.shift(),e.push({value:t,type:d[0].replace(aa," ")}),g=g.slice(t.length));for(f in G.filter)!(d=ea[f].exec(g))||k[f]&&!(d=k[f](d))||
(t=d.shift(),e.push({value:t,type:f,matches:d}),g=g.slice(t.length));if(!t)break}return c?g.length:g?b.error(a):R(a,l).slice(0)};return Z=b.compile=function(a,b){var c,d=[],e=[],f=ia[a+" "];if(!f){b||(b=ka(a));for(c=b.length;c--;)(f=A(b[c]))[O]?d.push(f):e.push(f);(f=ia(a,ac(e,d))).selector=a}return f},J=b.select=function(a,b,c,d){var e,f,g,k,l,t="function"==typeof a&&a,h=!d&&ka(a=t.selector||a);if(c=c||[],1===h.length){if(2<(f=h[0]=h[0].slice(0)).length&&"ID"===(g=f[0]).type&&9===b.nodeType&&x&&
G.relative[f[1].type]){if(!(b=(G.find.ID(g.matches[0].replace(ma,na),b)||[])[0]))return c;t&&(b=b.parentNode);a=a.slice(f.shift().value.length)}for(e=ea.needsContext.test(a)?0:f.length;e--&&(g=f[e],!G.relative[k=g.type]);)if((l=G.find[k])&&(d=l(g.matches[0].replace(ma,na),pa.test(f[0].type)&&m(b.parentNode)||b))){if(f.splice(e,1),!(a=d.length&&n(f)))return Q.apply(c,d),c;break}}return(t||Z(a,h))(d,b,!x,c,!b||pa.test(a)&&m(b.parentNode)||b),c},P.sortStable=O.split("").sort(V).join("")===O,P.detectDuplicates=
!!E,Aa(),P.sortDetached=e(function(a){return 1&a.compareDocumentPosition(L.createElement("fieldset"))}),e(function(a){return a.innerHTML="<a href='#'></a>","#"===a.firstChild.getAttribute("href")})||g("type|href|height|width",function(a,b,c){if(!c)return a.getAttribute(b,"type"===b.toLowerCase()?1:2)}),P.attributes&&e(function(a){return a.innerHTML="<input/>",a.firstChild.setAttribute("value",""),""===a.firstChild.getAttribute("value")})||g("value",function(a,b,c){if(!c&&"input"===a.nodeName.toLowerCase())return a.defaultValue}),
e(function(a){return null==a.getAttribute("disabled")})||g("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",function(a,b,c){var d;if(!c)return!0===a[b]?b.toLowerCase():(d=a.getAttributeNode(b))&&d.specified?d.value:null}),b}(u);d.find=oa;d.expr=oa.selectors;d.expr[":"]=d.expr.pseudos;d.uniqueSort=d.unique=oa.uniqueSort;d.text=oa.getText;d.isXMLDoc=oa.isXML;d.contains=oa.contains;d.escapeSelector=oa.escape;var va=function(a,
b,c){for(var f=[],e=void 0!==c;(a=a[b])&&9!==a.nodeType;)if(1===a.nodeType){if(e&&d(a).is(c))break;f.push(a)}return f},ub=function(a,b){for(var c=[];a;a=a.nextSibling)1===a.nodeType&&a!==b&&c.push(a);return c},vb=d.expr.match.needsContext,wb=/^<([a-z][^\/\0>:\x20\t\r\n\f]*)[\x20\t\r\n\f]*\/?>(?:<\/\1>|)$/i;d.filter=function(a,b,c){var f=b[0];return c&&(a=":not("+a+")"),1===b.length&&1===f.nodeType?d.find.matchesSelector(f,a)?[f]:[]:d.find.matches(a,d.grep(b,function(a){return 1===a.nodeType}))};d.fn.extend({find:function(a){var b,
c=this.length,f=this;if("string"!=typeof a)return this.pushStack(d(a).filter(function(){for(b=0;b<c;b++)if(d.contains(f[b],this))return!0}));var e=this.pushStack([]);for(b=0;b<c;b++)d.find(a,f[b],e);return 1<c?d.uniqueSort(e):e},filter:function(a){return this.pushStack(Q(this,a||[],!1))},not:function(a){return this.pushStack(Q(this,a||[],!0))},is:function(a){return!!Q(this,"string"==typeof a&&vb.test(a)?d(a):a||[],!1).length}});var cc=/^(?:\s*(<[\w\W]+>)[^>]*|#([\w-]+))$/;(d.fn.init=function(a,b,
c){var f,e;if(!a)return this;if(c=c||dc,"string"==typeof a){if(!(f="<"===a[0]&&">"===a[a.length-1]&&3<=a.length?[null,a,null]:cc.exec(a))||!f[1]&&b)return!b||b.jquery?(b||c).find(a):this.constructor(b).find(a);if(f[1]){if(b=b instanceof d?b[0]:b,d.merge(this,d.parseHTML(f[1],b&&b.nodeType?b.ownerDocument||b:B,!0)),wb.test(f[1])&&d.isPlainObject(b))for(f in b)A(this[f])?this[f](b[f]):this.attr(f,b[f]);return this}return(e=B.getElementById(f[2]))&&(this[0]=e,this.length=1),this}return a.nodeType?(this[0]=
a,this.length=1,this):A(a)?void 0!==c.ready?c.ready(a):a(d):d.makeArray(a,this)}).prototype=d.fn;var dc=d(B);var ec=/^(?:parents|prev(?:Until|All))/,fc={children:!0,contents:!0,next:!0,prev:!0};d.fn.extend({has:function(a){var b=d(a,this),c=b.length;return this.filter(function(){for(var a=0;a<c;a++)if(d.contains(this,b[a]))return!0})},closest:function(a,b){var c,f=0,e=this.length,g=[],k="string"!=typeof a&&d(a);if(!vb.test(a))for(;f<e;f++)for(c=this[f];c&&c!==b;c=c.parentNode)if(11>c.nodeType&&(k?
-1<k.index(c):1===c.nodeType&&d.find.matchesSelector(c,a))){g.push(c);break}return this.pushStack(1<g.length?d.uniqueSort(g):g)},index:function(a){return a?"string"==typeof a?ya.call(d(a),this[0]):ya.call(this,a.jquery?a[0]:a):this[0]&&this[0].parentNode?this.first().prevAll().length:-1},add:function(a,b){return this.pushStack(d.uniqueSort(d.merge(this.get(),d(a,b))))},addBack:function(a){return this.add(null==a?this.prevObject:this.prevObject.filter(a))}});d.each({parent:function(a){return(a=a.parentNode)&&
11!==a.nodeType?a:null},parents:function(a){return va(a,"parentNode")},parentsUntil:function(a,b,c){return va(a,"parentNode",c)},next:function(a){return h(a,"nextSibling")},prev:function(a){return h(a,"previousSibling")},nextAll:function(a){return va(a,"nextSibling")},prevAll:function(a){return va(a,"previousSibling")},nextUntil:function(a,b,c){return va(a,"nextSibling",c)},prevUntil:function(a,b,c){return va(a,"previousSibling",c)},siblings:function(a){return ub((a.parentNode||{}).firstChild,a)},
children:function(a){return ub(a.firstChild)},contents:function(a){return x(a,"iframe")?a.contentDocument:(x(a,"template")&&(a=a.content||a),d.merge([],a.childNodes))}},function(a,b){d.fn[a]=function(c,f){var e=d.map(this,b,c);return"Until"!==a.slice(-5)&&(f=c),f&&"string"==typeof f&&(e=d.filter(f,e)),1<this.length&&(fc[a]||d.uniqueSort(e),ec.test(a)&&e.reverse()),this.pushStack(e)}});var N=/[^\x20\t\r\n\f]+/g;d.Callbacks=function(a){a="string"==typeof a?E(a):d.extend({},a);var b,c,f,e,g=[],k=[],
l=-1,t=function(){e=e||a.once;for(f=b=!0;k.length;l=-1)for(c=k.shift();++l<g.length;)!1===g[l].apply(c[0],c[1])&&a.stopOnFalse&&(l=g.length,c=!1);a.memory||(c=!1);b=!1;e&&(g=c?[]:"")},h={add:function(){return g&&(c&&!b&&(l=g.length-1,k.push(c)),function Pb(b){d.each(b,function(b,c){A(c)?a.unique&&h.has(c)||g.push(c):c&&c.length&&"string"!==z(c)&&Pb(c)})}(arguments),c&&!b&&t()),this},remove:function(){return d.each(arguments,function(a,b){for(var c;-1<(c=d.inArray(b,g,c));)g.splice(c,1),c<=l&&l--}),
this},has:function(a){return a?-1<d.inArray(a,g):0<g.length},empty:function(){return g&&(g=[]),this},disable:function(){return e=k=[],g=c="",this},disabled:function(){return!g},lock:function(){return e=k=[],c||b||(g=c=""),this},locked:function(){return!!e},fireWith:function(a,c){return e||(c=[a,(c=c||[]).slice?c.slice():c],k.push(c),b||t()),this},fire:function(){return h.fireWith(this,arguments),this},fired:function(){return!!f}};return h};d.extend({Deferred:function(a){var b=[["notify","progress",
d.Callbacks("memory"),d.Callbacks("memory"),2],["resolve","done",d.Callbacks("once memory"),d.Callbacks("once memory"),0,"resolved"],["reject","fail",d.Callbacks("once memory"),d.Callbacks("once memory"),1,"rejected"]],c="pending",f={state:function(){return c},always:function(){return e.done(arguments).fail(arguments),this},"catch":function(a){return f.then(null,a)},pipe:function(){var a=arguments;return d.Deferred(function(c){d.each(b,function(b,d){var f=A(a[d[4]])&&a[d[4]];e[d[1]](function(){var a=
f&&f.apply(this,arguments);a&&A(a.promise)?a.promise().progress(c.notify).done(c.resolve).fail(c.reject):c[d[0]+"With"](this,f?[a]:arguments)})});a=null}).promise()},then:function(a,c,e){function f(a,b,c,e){return function(){var k=this,l=arguments,t=function(){var d;if(!(a<g)){if((d=c.apply(k,l))===b.promise())throw new TypeError("Thenable self-resolution");var t=d&&("object"==typeof d||"function"==typeof d)&&d.then;A(t)?e?t.call(d,f(g,b,m,e),f(g,b,q,e)):(g++,t.call(d,f(g,b,m,e),f(g,b,q,e),f(g,b,
m,b.notifyWith))):(c!==m&&(k=void 0,l=[d]),(e||b.resolveWith)(k,l))}},h=e?t:function(){try{t()}catch(sb){d.Deferred.exceptionHook&&d.Deferred.exceptionHook(sb,h.stackTrace),a+1>=g&&(c!==q&&(k=void 0,l=[sb]),b.rejectWith(k,l))}};a?h():(d.Deferred.getStackHook&&(h.stackTrace=d.Deferred.getStackHook()),u.setTimeout(h))}}var g=0;return d.Deferred(function(d){b[0][3].add(f(0,d,A(e)?e:m,d.notifyWith));b[1][3].add(f(0,d,A(a)?a:m));b[2][3].add(f(0,d,A(c)?c:q))}).promise()},promise:function(a){return null!=
a?d.extend(a,f):f}},e={};return d.each(b,function(a,d){var g=d[2],k=d[5];f[d[1]]=g.add;k&&g.add(function(){c=k},b[3-a][2].disable,b[3-a][3].disable,b[0][2].lock,b[0][3].lock);g.add(d[3].fire);e[d[0]]=function(){return e[d[0]+"With"](this===e?void 0:this,arguments),this};e[d[0]+"With"]=g.fireWith}),f.promise(e),a&&a.call(e,e),e},when:function(a){var b=arguments.length,c=b,f=Array(c),e=aa.call(arguments),g=d.Deferred(),k=function(a){return function(c){f[a]=this;e[a]=1<arguments.length?aa.call(arguments):
c;--b||g.resolveWith(f,e)}};if(1>=b&&(F(a,g.done(k(c)).resolve,g.reject,!b),"pending"===g.state()||A(e[c]&&e[c].then)))return g.then();for(;c--;)F(e[c],k(c),g.reject);return g.promise()}});var gc=/^(Eval|Internal|Range|Reference|Syntax|Type|URI)Error$/;d.Deferred.exceptionHook=function(a,b){u.console&&u.console.warn&&a&&gc.test(a.name)&&u.console.warn("jQuery.Deferred exception: "+a.message,a.stack,b)};d.readyException=function(a){u.setTimeout(function(){throw a;})};var Ta=d.Deferred();d.fn.ready=
function(a){return Ta.then(a)["catch"](function(a){d.readyException(a)}),this};d.extend({isReady:!1,readyWait:1,ready:function(a){(!0===a?--d.readyWait:d.isReady)||(d.isReady=!0,!0!==a&&0<--d.readyWait||Ta.resolveWith(B,[d]))}});d.ready.then=Ta.then;"complete"===B.readyState||"loading"!==B.readyState&&!B.documentElement.doScroll?u.setTimeout(d.ready):(B.addEventListener("DOMContentLoaded",M),u.addEventListener("load",M));var ha=function(a,b,c,f,e,g,k){var l=0,t=a.length,h=null==c;if("object"===z(c))for(l in e=
!0,c)ha(a,b,l,c[l],!0,g,k);else if(void 0!==f&&(e=!0,A(f)||(k=!0),h&&(k?(b.call(a,f),b=null):(h=b,b=function(a,b,c){return h.call(d(a),c)})),b))for(;l<t;l++)b(a[l],c,k?f:f.call(a[l],l,b(a[l],c)));return e?a:h?b.call(a):t?b(a[0],c):g},Lb=/^-ms-/,Mb=/-([a-z])/g,Ha=function(a){return 1===a.nodeType||9===a.nodeType||!+a.nodeType};r.uid=1;r.prototype={cache:function(a){var b=a[this.expando];return b||(b={},Ha(a)&&(a.nodeType?a[this.expando]=b:Object.defineProperty(a,this.expando,{value:b,configurable:!0}))),
b},set:function(a,b,c){var d;a=this.cache(a);if("string"==typeof b)a[n(b)]=c;else for(d in b)a[n(d)]=b[d];return a},get:function(a,b){return void 0===b?this.cache(a):a[this.expando]&&a[this.expando][n(b)]},access:function(a,b,c){return void 0===b||b&&"string"==typeof b&&void 0===c?this.get(a,b):(this.set(a,b,c),void 0!==c?c:b)},remove:function(a,b){var c=a[this.expando];if(void 0!==c){if(void 0!==b){var f=(b=Array.isArray(b)?b.map(n):(b=n(b))in c?[b]:b.match(N)||[]).length;for(;f--;)delete c[b[f]]}(void 0===
b||d.isEmptyObject(c))&&(a.nodeType?a[this.expando]=void 0:delete a[this.expando])}},hasData:function(a){a=a[this.expando];return void 0!==a&&!d.isEmptyObject(a)}};var C=new r,K=new r,Ob=/^(?:\{[\w\W]*\}|\[[\w\W]*\])$/,Nb=/[A-Z]/g;d.extend({hasData:function(a){return K.hasData(a)||C.hasData(a)},data:function(a,b,c){return K.access(a,b,c)},removeData:function(a,b){K.remove(a,b)},_data:function(a,b,c){return C.access(a,b,c)},_removeData:function(a,b){C.remove(a,b)}});d.fn.extend({data:function(a,b){var c,
d,e,g=this[0],k=g&&g.attributes;if(void 0===a){if(this.length&&(e=K.get(g),1===g.nodeType&&!C.get(g,"hasDataAttrs"))){for(c=k.length;c--;)k[c]&&0===(d=k[c].name).indexOf("data-")&&(d=n(d.slice(5)),v(g,d,e[d]));C.set(g,"hasDataAttrs",!0)}return e}return"object"==typeof a?this.each(function(){K.set(this,a)}):ha(this,function(b){var c;if(g&&void 0===b){if(void 0!==(c=K.get(g,a))||void 0!==(c=v(g,a)))return c}else this.each(function(){K.set(this,a,b)})},null,b,1<arguments.length,null,!0)},removeData:function(a){return this.each(function(){K.remove(this,
a)})}});d.extend({queue:function(a,b,c){var f;if(a)return b=(b||"fx")+"queue",f=C.get(a,b),c&&(!f||Array.isArray(c)?f=C.access(a,b,d.makeArray(c)):f.push(c)),f||[]},dequeue:function(a,b){b=b||"fx";var c=d.queue(a,b),f=c.length,e=c.shift(),g=d._queueHooks(a,b),k=function(){d.dequeue(a,b)};"inprogress"===e&&(e=c.shift(),f--);e&&("fx"===b&&c.unshift("inprogress"),delete g.stop,e.call(a,k,g));!f&&g&&g.empty.fire()},_queueHooks:function(a,b){var c=b+"queueHooks";return C.get(a,c)||C.access(a,c,{empty:d.Callbacks("once memory").add(function(){C.remove(a,
[b+"queue",c])})})}});d.fn.extend({queue:function(a,b){var c=2;return"string"!=typeof a&&(b=a,a="fx",c--),arguments.length<c?d.queue(this[0],a):void 0===b?this:this.each(function(){var c=d.queue(this,a,b);d._queueHooks(this,a);"fx"===a&&"inprogress"!==c[0]&&d.dequeue(this,a)})},dequeue:function(a){return this.each(function(){d.dequeue(this,a)})},clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a,b){var c,f=1,e=d.Deferred(),g=this,k=this.length,l=function(){--f||e.resolveWith(g,
[g])};"string"!=typeof a&&(b=a,a=void 0);for(a=a||"fx";k--;)(c=C.get(g[k],a+"queueHooks"))&&c.empty&&(f++,c.empty.add(l));return l(),e.promise(b)}});var xb=/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source,za=new RegExp("^(?:([+-])=|)("+xb+")([a-z%]*)$","i"),da=["Top","Right","Bottom","Left"],Ca=function(a,b){return"none"===(a=b||a).style.display||""===a.style.display&&d.contains(a.ownerDocument,a)&&"none"===d.css(a,"display")},yb=function(a,b,c,d){var e,f={};for(e in b)f[e]=a.style[e],a.style[e]=b[e];
c=c.apply(a,d||[]);for(e in b)a.style[e]=f[e];return c},Za={};d.fn.extend({show:function(){return ra(this,!0)},hide:function(){return ra(this)},toggle:function(a){return"boolean"==typeof a?a?this.show():this.hide():this.each(function(){Ca(this)?d(this).show():d(this).hide()})}});var zb=/^(?:checkbox|radio)$/i,ab=/<([a-z][^\/\0>\x20\t\r\n\f]+)/i,bb=/^$|^module$|\/(?:java|ecma)script/i,V={option:[1,"<select multiple='multiple'>","</select>"],thead:[1,"<table>","</table>"],col:[2,"<table><colgroup>",
"</colgroup></table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],_default:[0,"",""]};V.optgroup=V.option;V.tbody=V.tfoot=V.colgroup=V.caption=V.thead;V.th=V.td;var Qb=/<|&#?\w+;/;!function(){var a=B.createDocumentFragment().appendChild(B.createElement("div")),b=B.createElement("input");b.setAttribute("type","radio");b.setAttribute("checked","checked");b.setAttribute("name","t");a.appendChild(b);H.checkClone=a.cloneNode(!0).cloneNode(!0).lastChild.checked;
a.innerHTML="<textarea>x</textarea>";H.noCloneChecked=!!a.cloneNode(!0).lastChild.defaultValue}();var Ia=B.documentElement,hc=/^key/,ic=/^(?:mouse|pointer|contextmenu|drag|drop)|click/,Ab=/^([^.]*)(?:\.(.+)|)/;d.event={global:{},add:function(a,b,c,f,e){var g,k,l,t,h,p,m,q,n;if(h=C.get(a))for(c.handler&&(c=(g=c).handler,e=g.selector),e&&d.find.matchesSelector(Ia,e),c.guid||(c.guid=d.guid++),(t=h.events)||(t=h.events={}),(k=h.handle)||(k=h.handle=function(b){return"undefined"!=typeof d&&d.event.triggered!==
b.type?d.event.dispatch.apply(a,arguments):void 0}),h=(b=(b||"").match(N)||[""]).length;h--;){var r=n=(l=Ab.exec(b[h])||[])[1];l=(l[2]||"").split(".").sort();r&&(m=d.event.special[r]||{},r=(e?m.delegateType:m.bindType)||r,m=d.event.special[r]||{},p=d.extend({type:r,origType:n,data:f,handler:c,guid:c.guid,selector:e,needsContext:e&&d.expr.match.needsContext.test(e),namespace:l.join(".")},g),(q=t[r])||((q=t[r]=[]).delegateCount=0,m.setup&&!1!==m.setup.call(a,f,l,k)||a.addEventListener&&a.addEventListener(r,
k)),m.add&&(m.add.call(a,p),p.handler.guid||(p.handler.guid=c.guid)),e?q.splice(q.delegateCount++,0,p):q.push(p),d.event.global[r]=!0)}},remove:function(a,b,c,f,e){var g,k,l,h,m,p,q,n,r=C.hasData(a)&&C.get(a);if(r&&(h=r.events)){for(m=(b=(b||"").match(N)||[""]).length;m--;)if(l=Ab.exec(b[m])||[],p=n=l[1],q=(l[2]||"").split(".").sort(),p){var v=d.event.special[p]||{};var u=h[p=(f?v.delegateType:v.bindType)||p]||[];l=l[2]&&new RegExp("(^|\\.)"+q.join("\\.(?:.*\\.|)")+"(\\.|$)");for(k=g=u.length;g--;){var A=
u[g];!e&&n!==A.origType||c&&c.guid!==A.guid||l&&!l.test(A.namespace)||f&&f!==A.selector&&("**"!==f||!A.selector)||(u.splice(g,1),A.selector&&u.delegateCount--,v.remove&&v.remove.call(a,A))}k&&!u.length&&(v.teardown&&!1!==v.teardown.call(a,q,r.handle)||d.removeEvent(a,p,r.handle),delete h[p])}else for(p in h)d.event.remove(a,p+b[m],c,f,!0);d.isEmptyObject(h)&&C.remove(a,"handle events")}},dispatch:function(a){var b=d.event.fix(a),c,f,e,g,k=Array(arguments.length);var l=(C.get(this,"events")||{})[b.type]||
[];var h=d.event.special[b.type]||{};k[0]=b;for(c=1;c<arguments.length;c++)k[c]=arguments[c];if(b.delegateTarget=this,!h.preDispatch||!1!==h.preDispatch.call(this,b)){var m=d.event.handlers.call(this,b,l);for(c=0;(e=m[c++])&&!b.isPropagationStopped();)for(b.currentTarget=e.elem,l=0;(g=e.handlers[l++])&&!b.isImmediatePropagationStopped();)b.rnamespace&&!b.rnamespace.test(g.namespace)||(b.handleObj=g,b.data=g.data,void 0!==(f=((d.event.special[g.origType]||{}).handle||g.handler).apply(e.elem,k))&&!1===
(b.result=f)&&(b.preventDefault(),b.stopPropagation()));return h.postDispatch&&h.postDispatch.call(this,b),b.result}},handlers:function(a,b){var c,f,e,g=[],k=b.delegateCount,l=a.target;if(k&&l.nodeType&&!("click"===a.type&&1<=a.button))for(;l!==this;l=l.parentNode||this)if(1===l.nodeType&&("click"!==a.type||!0!==l.disabled)){var h=[];var m={};for(c=0;c<k;c++)void 0===m[e=(f=b[c]).selector+" "]&&(m[e]=f.needsContext?-1<d(e,this).index(l):d.find(e,this,null,[l]).length),m[e]&&h.push(f);h.length&&g.push({elem:l,
handlers:h})}return l=this,k<b.length&&g.push({elem:l,handlers:b.slice(k)}),g},addProp:function(a,b){Object.defineProperty(d.Event.prototype,a,{enumerable:!0,configurable:!0,get:A(b)?function(){if(this.originalEvent)return b(this.originalEvent)}:function(){if(this.originalEvent)return this.originalEvent[a]},set:function(b){Object.defineProperty(this,a,{enumerable:!0,configurable:!0,writable:!0,value:b})}})},fix:function(a){return a[d.expando]?a:new d.Event(a)},special:{load:{noBubble:!0},focus:{trigger:function(){if(this!==
cb()&&this.focus)return this.focus(),!1},delegateType:"focusin"},blur:{trigger:function(){if(this===cb()&&this.blur)return this.blur(),!1},delegateType:"focusout"},click:{trigger:function(){if("checkbox"===this.type&&this.click&&x(this,"input"))return this.click(),!1},_default:function(a){return x(a.target,"a")}},beforeunload:{postDispatch:function(a){void 0!==a.result&&a.originalEvent&&(a.originalEvent.returnValue=a.result)}}}};d.removeEvent=function(a,b,c){a.removeEventListener&&a.removeEventListener(b,
c)};d.Event=function(a,b){if(!(this instanceof d.Event))return new d.Event(a,b);a&&a.type?(this.originalEvent=a,this.type=a.type,this.isDefaultPrevented=a.defaultPrevented||void 0===a.defaultPrevented&&!1===a.returnValue?Da:sa,this.target=a.target&&3===a.target.nodeType?a.target.parentNode:a.target,this.currentTarget=a.currentTarget,this.relatedTarget=a.relatedTarget):this.type=a;b&&d.extend(this,b);this.timeStamp=a&&a.timeStamp||Date.now();this[d.expando]=!0};d.Event.prototype={constructor:d.Event,
isDefaultPrevented:sa,isPropagationStopped:sa,isImmediatePropagationStopped:sa,isSimulated:!1,preventDefault:function(){var a=this.originalEvent;this.isDefaultPrevented=Da;a&&!this.isSimulated&&a.preventDefault()},stopPropagation:function(){var a=this.originalEvent;this.isPropagationStopped=Da;a&&!this.isSimulated&&a.stopPropagation()},stopImmediatePropagation:function(){var a=this.originalEvent;this.isImmediatePropagationStopped=Da;a&&!this.isSimulated&&a.stopImmediatePropagation();this.stopPropagation()}};
d.each({altKey:!0,bubbles:!0,cancelable:!0,changedTouches:!0,ctrlKey:!0,detail:!0,eventPhase:!0,metaKey:!0,pageX:!0,pageY:!0,shiftKey:!0,view:!0,"char":!0,charCode:!0,key:!0,keyCode:!0,button:!0,buttons:!0,clientX:!0,clientY:!0,offsetX:!0,offsetY:!0,pointerId:!0,pointerType:!0,screenX:!0,screenY:!0,targetTouches:!0,toElement:!0,touches:!0,which:function(a){var b=a.button;return null==a.which&&hc.test(a.type)?null!=a.charCode?a.charCode:a.keyCode:!a.which&&void 0!==b&&ic.test(a.type)?1&b?1:2&b?3:4&
b?2:0:a.which}},d.event.addProp);d.each({mouseenter:"mouseover",mouseleave:"mouseout",pointerenter:"pointerover",pointerleave:"pointerout"},function(a,b){d.event.special[a]={delegateType:b,bindType:b,handle:function(a){var c,e=a.relatedTarget,g=a.handleObj;return e&&(e===this||d.contains(this,e))||(a.type=g.origType,c=g.handler.apply(this,arguments),a.type=b),c}}});d.fn.extend({on:function(a,b,c,d){return Ka(this,a,b,c,d)},one:function(a,b,c,d){return Ka(this,a,b,c,d,1)},off:function(a,b,c){var f,
e;if(a&&a.preventDefault&&a.handleObj)return f=a.handleObj,d(a.delegateTarget).off(f.namespace?f.origType+"."+f.namespace:f.origType,f.selector,f.handler),this;if("object"==typeof a){for(e in a)this.off(e,b,a[e]);return this}return!1!==b&&"function"!=typeof b||(c=b,b=void 0),!1===c&&(c=sa),this.each(function(){d.event.remove(this,a,c,b)})}});var jc=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([a-z][^\/\0>\x20\t\r\n\f]*)[^>]*)\/>/gi,kc=/<script|<style|<link/i,Tb=/checked\s*(?:[^=]|=\s*.checked.)/i,
Ub=/^\s*<!(?:\[CDATA\[|--)|(?:\]\]|--)>\s*$/g;d.extend({htmlPrefilter:function(a){return a.replace(jc,"<$1></$2>")},clone:function(a,b,c){var f,e,g=a.cloneNode(!0),k=d.contains(a.ownerDocument,a);if(!(H.noCloneChecked||1!==a.nodeType&&11!==a.nodeType||d.isXMLDoc(a))){var l=U(g);var h=0;for(f=(e=U(a)).length;h<f;h++){var m=e[h],p=l[h],q=p.nodeName.toLowerCase();"input"===q&&zb.test(m.type)?p.checked=m.checked:"input"!==q&&"textarea"!==q||(p.defaultValue=m.defaultValue)}}if(b)if(c)for(e=e||U(a),l=l||
U(g),h=0,f=e.length;h<f;h++)eb(e[h],l[h]);else eb(a,g);return 0<(l=U(g,"script")).length&&Ja(l,!k&&U(a,"script")),g},cleanData:function(a){for(var b,c,f,e=d.event.special,g=0;void 0!==(c=a[g]);g++)if(Ha(c)){if(b=c[C.expando]){if(b.events)for(f in b.events)e[f]?d.event.remove(c,f):d.removeEvent(c,f,b.handle);c[C.expando]=void 0}c[K.expando]&&(c[K.expando]=void 0)}}});d.fn.extend({detach:function(a){return gb(this,a,!0)},remove:function(a){return gb(this,a)},text:function(a){return ha(this,function(a){return void 0===
a?d.text(this):this.empty().each(function(){1!==this.nodeType&&11!==this.nodeType&&9!==this.nodeType||(this.textContent=a)})},null,a,arguments.length)},append:function(){return ta(this,arguments,function(a){1!==this.nodeType&&11!==this.nodeType&&9!==this.nodeType||db(this,a).appendChild(a)})},prepend:function(){return ta(this,arguments,function(a){if(1===this.nodeType||11===this.nodeType||9===this.nodeType){var b=db(this,a);b.insertBefore(a,b.firstChild)}})},before:function(){return ta(this,arguments,
function(a){this.parentNode&&this.parentNode.insertBefore(a,this)})},after:function(){return ta(this,arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this.nextSibling)})},empty:function(){for(var a,b=0;null!=(a=this[b]);b++)1===a.nodeType&&(d.cleanData(U(a,!1)),a.textContent="");return this},clone:function(a,b){return a=null!=a&&a,b=null==b?a:b,this.map(function(){return d.clone(this,a,b)})},html:function(a){return ha(this,function(a){var b=this[0]||{},f=0,e=this.length;if(void 0===
a&&1===b.nodeType)return b.innerHTML;if("string"==typeof a&&!kc.test(a)&&!V[(ab.exec(a)||["",""])[1].toLowerCase()]){a=d.htmlPrefilter(a);try{for(;f<e;f++)1===(b=this[f]||{}).nodeType&&(d.cleanData(U(b,!1)),b.innerHTML=a);b=0}catch(g){}}b&&this.empty().append(a)},null,a,arguments.length)},replaceWith:function(){var a=[];return ta(this,arguments,function(b){var c=this.parentNode;0>d.inArray(this,a)&&(d.cleanData(U(this)),c&&c.replaceChild(b,this))},a)}});d.each({appendTo:"append",prependTo:"prepend",
insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){d.fn[a]=function(a){for(var c=[],e=d(a),g=e.length-1,k=0;k<=g;k++)a=k===g?this:this.clone(!0),d(e[k])[b](a),Sa.apply(c,a.get());return this.pushStack(c)}});var La=new RegExp("^("+xb+")(?!px)[a-z%]+$","i"),ua=function(a){var b=a.ownerDocument.defaultView;return b&&b.opener||(b=u),b.getComputedStyle(a)},Vb=new RegExp(da.join("|"),"i");!function(){function a(){if(l){k.style.cssText="position:absolute;left:-11111px;width:60px;margin-top:1px;padding:0;border:0";
l.style.cssText="position:relative;display:block;box-sizing:border-box;overflow:scroll;margin:auto;border:1px;padding:1px;width:60%;top:1%";Ia.appendChild(k).appendChild(l);var a=u.getComputedStyle(l);b="1%"!==a.top;g=12===Math.round(parseFloat(a.marginLeft));l.style.right="60%";e=36===Math.round(parseFloat(a.right));c=36===Math.round(parseFloat(a.width));l.style.position="absolute";f=36===l.offsetWidth||"absolute";Ia.removeChild(k);l=null}}var b,c,f,e,g,k=B.createElement("div"),l=B.createElement("div");
l.style&&(l.style.backgroundClip="content-box",l.cloneNode(!0).style.backgroundClip="",H.clearCloneStyle="content-box"===l.style.backgroundClip,d.extend(H,{boxSizingReliable:function(){return a(),c},pixelBoxStyles:function(){return a(),e},pixelPosition:function(){return a(),b},reliableMarginLeft:function(){return a(),g},scrollboxSize:function(){return a(),f}}))}();var lc=/^(none|table(?!-c[ea]).+)/,Bb=/^--/,mc={position:"absolute",visibility:"hidden",display:"block"},Cb={letterSpacing:"0",fontWeight:"400"},
kb=["Webkit","Moz","ms"],jb=B.createElement("div").style;d.extend({cssHooks:{opacity:{get:function(a,b){if(b)return a=ca(a,"opacity"),""===a?"1":a}}},cssNumber:{animationIterationCount:!0,columnCount:!0,fillOpacity:!0,flexGrow:!0,flexShrink:!0,fontWeight:!0,lineHeight:!0,opacity:!0,order:!0,orphans:!0,widows:!0,zIndex:!0,zoom:!0},cssProps:{},style:function(a,b,c,f){if(a&&3!==a.nodeType&&8!==a.nodeType&&a.style){var e,g,k,l=n(b),h=Bb.test(b),m=a.style;if(h||(b=ib(l)),k=d.cssHooks[b]||d.cssHooks[l],
void 0===c)return k&&"get"in k&&void 0!==(e=k.get(a,!1,f))?e:m[b];"string"==(g=typeof c)&&(e=za.exec(c))&&e[1]&&(c=Ya(a,b,e),g="number");null!=c&&c===c&&("number"===g&&(c+=e&&e[3]||(d.cssNumber[l]?"":"px")),H.clearCloneStyle||""!==c||0!==b.indexOf("background")||(m[b]="inherit"),k&&"set"in k&&void 0===(c=k.set(a,c,f))||(h?m.setProperty(b,c):m[b]=c))}},css:function(a,b,c,f){var e,g,k,l=n(b);return Bb.test(b)||(b=ib(l)),(k=d.cssHooks[b]||d.cssHooks[l])&&"get"in k&&(e=k.get(a,!0,c)),void 0===e&&(e=ca(a,
b,f)),"normal"===e&&b in Cb&&(e=Cb[b]),""===c||c?(g=parseFloat(e),!0===c||isFinite(g)?g||0:e):e}});d.each(["height","width"],function(a,b){d.cssHooks[b]={get:function(a,f,e){if(f)return!lc.test(d.css(a,"display"))||a.getClientRects().length&&a.getBoundingClientRect().width?mb(a,b,e):yb(a,mc,function(){return mb(a,b,e)})},set:function(a,f,e){var c,k=ua(a),l="border-box"===d.css(a,"boxSizing",!1,k);e=e&&Ma(a,b,e,l,k);return l&&H.scrollboxSize()===k.position&&(e-=Math.ceil(a["offset"+b[0].toUpperCase()+
b.slice(1)]-parseFloat(k[b])-Ma(a,b,"border",!1,k)-.5)),e&&(c=za.exec(f))&&"px"!==(c[3]||"px")&&(a.style[b]=f,f=d.css(a,b)),lb(a,f,e)}}});d.cssHooks.marginLeft=hb(H.reliableMarginLeft,function(a,b){if(b)return(parseFloat(ca(a,"marginLeft"))||a.getBoundingClientRect().left-yb(a,{marginLeft:0},function(){return a.getBoundingClientRect().left}))+"px"});d.each({margin:"",padding:"",border:"Width"},function(a,b){d.cssHooks[a+b]={expand:function(c){var d=0,e={};for(c="string"==typeof c?c.split(" "):[c];4>
d;d++)e[a+da[d]+b]=c[d]||c[d-2]||c[0];return e}};"margin"!==a&&(d.cssHooks[a+b].set=lb)});d.fn.extend({css:function(a,b){return ha(this,function(a,b,e){var c,f={},l=0;if(Array.isArray(b)){e=ua(a);for(c=b.length;l<c;l++)f[b[l]]=d.css(a,b[l],!1,e);return f}return void 0!==e?d.style(a,b,e):d.css(a,b)},a,b,1<arguments.length)}});d.Tween=R;R.prototype={constructor:R,init:function(a,b,c,f,e,g){this.elem=a;this.prop=c;this.easing=e||d.easing._default;this.options=b;this.start=this.now=this.cur();this.end=
f;this.unit=g||(d.cssNumber[c]?"":"px")},cur:function(){var a=R.propHooks[this.prop];return a&&a.get?a.get(this):R.propHooks._default.get(this)},run:function(a){var b,c=R.propHooks[this.prop];return this.options.duration?this.pos=b=d.easing[this.easing](a,this.options.duration*a,0,1,this.options.duration):this.pos=b=a,this.now=(this.end-this.start)*b+this.start,this.options.step&&this.options.step.call(this.elem,this.now,this),c&&c.set?c.set(this):R.propHooks._default.set(this),this}};R.prototype.init.prototype=
R.prototype;R.propHooks={_default:{get:function(a){var b;return 1!==a.elem.nodeType||null!=a.elem[a.prop]&&null==a.elem.style[a.prop]?a.elem[a.prop]:(b=d.css(a.elem,a.prop,""))&&"auto"!==b?b:0},set:function(a){d.fx.step[a.prop]?d.fx.step[a.prop](a):1!==a.elem.nodeType||null==a.elem.style[d.cssProps[a.prop]]&&!d.cssHooks[a.prop]?a.elem[a.prop]=a.now:d.style(a.elem,a.prop,a.now+a.unit)}}};R.propHooks.scrollTop=R.propHooks.scrollLeft={set:function(a){a.elem.nodeType&&a.elem.parentNode&&(a.elem[a.prop]=
a.now)}};d.easing={linear:function(a){return a},swing:function(a){return.5-Math.cos(a*Math.PI)/2},_default:"swing"};d.fx=R.prototype.init;d.fx.step={};var ea,ka,nc=/^(?:toggle|show|hide)$/,oc=/queueHooks$/;d.Animation=d.extend(Y,{tweeners:{"*":[function(a,b){var c=this.createTween(a,b);return Ya(c.elem,a,za.exec(b),c),c}]},tweener:function(a,b){A(a)?(b=a,a=["*"]):a=a.match(N);for(var c,d=0,e=a.length;d<e;d++)c=a[d],Y.tweeners[c]=Y.tweeners[c]||[],Y.tweeners[c].unshift(b)},prefilters:[function(a,b,
c){var f,e,g,k,l,h,m,p="width"in b||"height"in b,q=this,n={},r=a.style,v=a.nodeType&&Ca(a),u=C.get(a,"fxshow");c.queue||(null==(k=d._queueHooks(a,"fx")).unqueued&&(k.unqueued=0,l=k.empty.fire,k.empty.fire=function(){k.unqueued||l()}),k.unqueued++,q.always(function(){q.always(function(){k.unqueued--;d.queue(a,"fx").length||k.empty.fire()})}));for(f in b)if(e=b[f],nc.test(e)){if(delete b[f],g=g||"toggle"===e,e===(v?"hide":"show")){if("show"!==e||!u||void 0===u[f])continue;v=!0}n[f]=u&&u[f]||d.style(a,
f)}if((b=!d.isEmptyObject(b))||!d.isEmptyObject(n))for(f in p&&1===a.nodeType&&(c.overflow=[r.overflow,r.overflowX,r.overflowY],null==(h=u&&u.display)&&(h=C.get(a,"display")),"none"===(m=d.css(a,"display"))&&(h?m=h:(ra([a],!0),h=a.style.display||h,m=d.css(a,"display"),ra([a]))),("inline"===m||"inline-block"===m&&null!=h)&&"none"===d.css(a,"float")&&(b||(q.done(function(){r.display=h}),null==h&&(m=r.display,h="none"===m?"":m)),r.display="inline-block")),c.overflow&&(r.overflow="hidden",q.always(function(){r.overflow=
c.overflow[0];r.overflowX=c.overflow[1];r.overflowY=c.overflow[2]})),b=!1,n)b||(u?"hidden"in u&&(v=u.hidden):u=C.access(a,"fxshow",{display:h}),g&&(u.hidden=!v),v&&ra([a],!0),q.done(function(){v||ra([a]);C.remove(a,"fxshow");for(f in n)d.style(a,f,n[f])})),b=ob(v?u[f]:0,f,q),f in u||(u[f]=b.start,v&&(b.end=b.start,b.start=0))}],prefilter:function(a,b){b?Y.prefilters.unshift(a):Y.prefilters.push(a)}});d.speed=function(a,b,c){var f=a&&"object"==typeof a?d.extend({},a):{complete:c||!c&&b||A(a)&&a,duration:a,
easing:c&&b||b&&!A(b)&&b};return d.fx.off?f.duration=0:"number"!=typeof f.duration&&(f.duration in d.fx.speeds?f.duration=d.fx.speeds[f.duration]:f.duration=d.fx.speeds._default),null!=f.queue&&!0!==f.queue||(f.queue="fx"),f.old=f.complete,f.complete=function(){A(f.old)&&f.old.call(this);f.queue&&d.dequeue(this,f.queue)},f};d.fn.extend({fadeTo:function(a,b,c,d){return this.filter(Ca).css("opacity",0).show().end().animate({opacity:b},a,c,d)},animate:function(a,b,c,f){var e=d.isEmptyObject(a),g=d.speed(b,
c,f);b=function(){var b=Y(this,d.extend({},a),g);(e||C.get(this,"finish"))&&b.stop(!0)};return b.finish=b,e||!1===g.queue?this.each(b):this.queue(g.queue,b)},stop:function(a,b,c){var f=function(a){var b=a.stop;delete a.stop;b(c)};return"string"!=typeof a&&(c=b,b=a,a=void 0),b&&!1!==a&&this.queue(a||"fx",[]),this.each(function(){var b=!0,g=null!=a&&a+"queueHooks",k=d.timers,h=C.get(this);if(g)h[g]&&h[g].stop&&f(h[g]);else for(g in h)h[g]&&h[g].stop&&oc.test(g)&&f(h[g]);for(g=k.length;g--;)k[g].elem!==
this||null!=a&&k[g].queue!==a||(k[g].anim.stop(c),b=!1,k.splice(g,1));!b&&c||d.dequeue(this,a)})},finish:function(a){return!1!==a&&(a=a||"fx"),this.each(function(){var b=C.get(this),c=b[a+"queue"];var f=b[a+"queueHooks"];var e=d.timers,g=c?c.length:0;b.finish=!0;d.queue(this,a,[]);f&&f.stop&&f.stop.call(this,!0);for(f=e.length;f--;)e[f].elem===this&&e[f].queue===a&&(e[f].anim.stop(!0),e.splice(f,1));for(f=0;f<g;f++)c[f]&&c[f].finish&&c[f].finish.call(this);delete b.finish})}});d.each(["toggle","show",
"hide"],function(a,b){var c=d.fn[b];d.fn[b]=function(a,d,g){return null==a||"boolean"==typeof a?c.apply(this,arguments):this.animate(Fa(b,!0),a,d,g)}});d.each({slideDown:Fa("show"),slideUp:Fa("hide"),slideToggle:Fa("toggle"),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){d.fn[a]=function(a,d,e){return this.animate(b,a,d,e)}});d.timers=[];d.fx.tick=function(){var a,b=0,c=d.timers;for(ea=Date.now();b<c.length;b++)(a=c[b])()||c[b]!==a||c.splice(b--,1);c.length||
d.fx.stop();ea=void 0};d.fx.timer=function(a){d.timers.push(a);d.fx.start()};d.fx.interval=13;d.fx.start=function(){ka||(ka=!0,Na())};d.fx.stop=function(){ka=null};d.fx.speeds={slow:600,fast:200,_default:400};d.fn.delay=function(a,b){return a=d.fx?d.fx.speeds[a]||a:a,b=b||"fx",this.queue(b,function(b,d){var c=u.setTimeout(b,a);d.stop=function(){u.clearTimeout(c)}})};(function(){var a=B.createElement("input"),b=B.createElement("select").appendChild(B.createElement("option"));a.type="checkbox";H.checkOn=
""!==a.value;H.optSelected=b.selected;(a=B.createElement("input")).value="t";a.type="radio";H.radioValue="t"===a.value})();var Ba=d.expr.attrHandle;d.fn.extend({attr:function(a,b){return ha(this,d.attr,a,b,1<arguments.length)},removeAttr:function(a){return this.each(function(){d.removeAttr(this,a)})}});d.extend({attr:function(a,b,c){var f,e,g=a.nodeType;if(3!==g&&8!==g&&2!==g)return"undefined"==typeof a.getAttribute?d.prop(a,b,c):(1===g&&d.isXMLDoc(a)||(e=d.attrHooks[b.toLowerCase()]||(d.expr.match.bool.test(b)?
pc:void 0)),void 0!==c?null===c?void d.removeAttr(a,b):e&&"set"in e&&void 0!==(f=e.set(a,c,b))?f:(a.setAttribute(b,c+""),c):e&&"get"in e&&null!==(f=e.get(a,b))?f:null==(f=d.find.attr(a,b))?void 0:f)},attrHooks:{type:{set:function(a,b){if(!H.radioValue&&"radio"===b&&x(a,"input")){var c=a.value;return a.setAttribute("type",b),c&&(a.value=c),b}}}},removeAttr:function(a,b){var c=0,d=b&&b.match(N);if(d&&1===a.nodeType)for(;b=d[c++];)a.removeAttribute(b)}});var pc={set:function(a,b,c){return!1===b?d.removeAttr(a,
c):a.setAttribute(c,c),c}};d.each(d.expr.match.bool.source.match(/\w+/g),function(a,b){var c=Ba[b]||d.find.attr;Ba[b]=function(a,b,d){var e,f,g=b.toLowerCase();return d||(f=Ba[g],Ba[g]=e,e=null!=c(a,b,d)?g:null,Ba[g]=f),e}});var qc=/^(?:input|select|textarea|button)$/i,rc=/^(?:a|area)$/i;d.fn.extend({prop:function(a,b){return ha(this,d.prop,a,b,1<arguments.length)},removeProp:function(a){return this.each(function(){delete this[d.propFix[a]||a]})}});d.extend({prop:function(a,b,c){var f,e,g=a.nodeType;
if(3!==g&&8!==g&&2!==g)return 1===g&&d.isXMLDoc(a)||(b=d.propFix[b]||b,e=d.propHooks[b]),void 0!==c?e&&"set"in e&&void 0!==(f=e.set(a,c,b))?f:a[b]=c:e&&"get"in e&&null!==(f=e.get(a,b))?f:a[b]},propHooks:{tabIndex:{get:function(a){var b=d.find.attr(a,"tabindex");return b?parseInt(b,10):qc.test(a.nodeName)||rc.test(a.nodeName)&&a.href?0:-1}}},propFix:{"for":"htmlFor","class":"className"}});H.optSelected||(d.propHooks.selected={get:function(a){a=a.parentNode;return a&&a.parentNode&&a.parentNode.selectedIndex,
null},set:function(a){a=a.parentNode;a&&(a.selectedIndex,a.parentNode&&a.parentNode.selectedIndex)}});d.each("tabIndex readOnly maxLength cellSpacing cellPadding rowSpan colSpan useMap frameBorder contentEditable".split(" "),function(){d.propFix[this.toLowerCase()]=this});d.fn.extend({addClass:function(a){var b,c,f,e,g,k,h,m=0;if(A(a))return this.each(function(b){d(this).addClass(a.call(this,b,X(this)))});if((b=Oa(a)).length)for(;c=this[m++];)if(e=X(c),f=1===c.nodeType&&" "+ja(e)+" "){for(k=0;g=b[k++];)0>
f.indexOf(" "+g+" ")&&(f+=g+" ");e!==(h=ja(f))&&c.setAttribute("class",h)}return this},removeClass:function(a){var b,c,f,e,g,k,h,m=0;if(A(a))return this.each(function(b){d(this).removeClass(a.call(this,b,X(this)))});if(!arguments.length)return this.attr("class","");if((b=Oa(a)).length)for(;c=this[m++];)if(e=X(c),f=1===c.nodeType&&" "+ja(e)+" "){for(k=0;g=b[k++];)for(;-1<f.indexOf(" "+g+" ");)f=f.replace(" "+g+" "," ");e!==(h=ja(f))&&c.setAttribute("class",h)}return this},toggleClass:function(a,b){var c=
typeof a,f="string"===c||Array.isArray(a);return"boolean"==typeof b&&f?b?this.addClass(a):this.removeClass(a):A(a)?this.each(function(c){d(this).toggleClass(a.call(this,c,X(this),b),b)}):this.each(function(){var b,g;if(f){var k=0;var h=d(this);for(g=Oa(a);b=g[k++];)h.hasClass(b)?h.removeClass(b):h.addClass(b)}else void 0!==a&&"boolean"!==c||((b=X(this))&&C.set(this,"__className__",b),this.setAttribute&&this.setAttribute("class",b||!1===a?"":C.get(this,"__className__")||""))})},hasClass:function(a){var b,
c=0;for(a=" "+a+" ";b=this[c++];)if(1===b.nodeType&&-1<(" "+ja(X(b))+" ").indexOf(a))return!0;return!1}});var sc=/\r/g;d.fn.extend({val:function(a){var b,c,f,e=this[0];if(arguments.length)return f=A(a),this.each(function(c){var e;1===this.nodeType&&(null==(e=f?a.call(this,c,d(this).val()):a)?e="":"number"==typeof e?e+="":Array.isArray(e)&&(e=d.map(e,function(a){return null==a?"":a+""})),(b=d.valHooks[this.type]||d.valHooks[this.nodeName.toLowerCase()])&&"set"in b&&void 0!==b.set(this,e,"value")||
(this.value=e))});if(e)return(b=d.valHooks[e.type]||d.valHooks[e.nodeName.toLowerCase()])&&"get"in b&&void 0!==(c=b.get(e,"value"))?c:"string"==typeof(c=e.value)?c.replace(sc,""):null==c?"":c}});d.extend({valHooks:{option:{get:function(a){var b=d.find.attr(a,"value");return null!=b?b:ja(d.text(a))}},select:{get:function(a){var b,c,f=a.options,e=a.selectedIndex,g="select-one"===a.type,k=g?null:[],h=g?e+1:f.length;for(c=0>e?h:g?e:0;c<h;c++)if(!(!(b=f[c]).selected&&c!==e||b.disabled||b.parentNode.disabled&&
x(b.parentNode,"optgroup"))){if(a=d(b).val(),g)return a;k.push(a)}return k},set:function(a,b){var c,f,e=a.options;b=d.makeArray(b);for(var g=e.length;g--;)((f=e[g]).selected=-1<d.inArray(d.valHooks.option.get(f),b))&&(c=!0);return c||(a.selectedIndex=-1),b}}}});d.each(["radio","checkbox"],function(){d.valHooks[this]={set:function(a,b){if(Array.isArray(b))return a.checked=-1<d.inArray(d(a).val(),b)}};H.checkOn||(d.valHooks[this].get=function(a){return null===a.getAttribute("value")?"on":a.value})});
H.focusin="onfocusin"in u;var Db=/^(?:focusinfocus|focusoutblur)$/,Eb=function(a){a.stopPropagation()};d.extend(d.event,{trigger:function(a,b,c,f){var e,g,k,h,m,q,p=[c||B],n=Ga.call(a,"type")?a.type:a;var r=Ga.call(a,"namespace")?a.namespace.split("."):[];if(e=q=g=c=c||B,3!==c.nodeType&&8!==c.nodeType&&!Db.test(n+d.event.triggered)&&(-1<n.indexOf(".")&&(n=(r=n.split(".")).shift(),r.sort()),k=0>n.indexOf(":")&&"on"+n,a=a[d.expando]?a:new d.Event(n,"object"==typeof a&&a),a.isTrigger=f?2:3,a.namespace=
r.join("."),a.rnamespace=a.namespace?new RegExp("(^|\\.)"+r.join("\\.(?:.*\\.|)")+"(\\.|$)"):null,a.result=void 0,a.target||(a.target=c),b=null==b?[a]:d.makeArray(b,[a]),m=d.event.special[n]||{},f||!m.trigger||!1!==m.trigger.apply(c,b))){if(!f&&!m.noBubble&&!qa(c)){var v=m.delegateType||n;for(Db.test(v+n)||(e=e.parentNode);e;e=e.parentNode)p.push(e),g=e;g===(c.ownerDocument||B)&&p.push(g.defaultView||g.parentWindow||u)}for(r=0;(e=p[r++])&&!a.isPropagationStopped();)q=e,a.type=1<r?v:m.bindType||n,
(h=(C.get(e,"events")||{})[a.type]&&C.get(e,"handle"))&&h.apply(e,b),(h=k&&e[k])&&h.apply&&Ha(e)&&(a.result=h.apply(e,b),!1===a.result&&a.preventDefault());return a.type=n,f||a.isDefaultPrevented()||m._default&&!1!==m._default.apply(p.pop(),b)||!Ha(c)||k&&A(c[n])&&!qa(c)&&((g=c[k])&&(c[k]=null),d.event.triggered=n,a.isPropagationStopped()&&q.addEventListener(n,Eb),c[n](),a.isPropagationStopped()&&q.removeEventListener(n,Eb),d.event.triggered=void 0,g&&(c[k]=g)),a.result}},simulate:function(a,b,c){a=
d.extend(new d.Event,c,{type:a,isSimulated:!0});d.event.trigger(a,null,b)}});d.fn.extend({trigger:function(a,b){return this.each(function(){d.event.trigger(a,b,this)})},triggerHandler:function(a,b){var c=this[0];if(c)return d.event.trigger(a,b,c,!0)}});H.focusin||d.each({focus:"focusin",blur:"focusout"},function(a,b){var c=function(a){d.event.simulate(b,a.target,d.event.fix(a))};d.event.special[b]={setup:function(){var d=this.ownerDocument||this,e=C.access(d,b);e||d.addEventListener(a,c,!0);C.access(d,
b,(e||0)+1)},teardown:function(){var d=this.ownerDocument||this,e=C.access(d,b)-1;e?C.access(d,b,e):(d.removeEventListener(a,c,!0),C.remove(d,b))}}});var pa=u.location,Fb=Date.now(),Ua=/\?/;d.parseXML=function(a){if(!a||"string"!=typeof a)return null;try{var b=(new u.DOMParser).parseFromString(a,"text/xml")}catch(c){b=void 0}return b&&!b.getElementsByTagName("parsererror").length||d.error("Invalid XML: "+a),b};var Xb=/\[\]$/,Gb=/\r?\n/g,tc=/^(?:submit|button|image|reset|file)$/i,uc=/^(?:input|select|textarea|keygen)/i;
d.param=function(a,b){var c,f=[],e=function(a,b){b=A(b)?b():b;f[f.length]=encodeURIComponent(a)+"="+encodeURIComponent(null==b?"":b)};if(Array.isArray(a)||a.jquery&&!d.isPlainObject(a))d.each(a,function(){e(this.name,this.value)});else for(c in a)Pa(c,a[c],b,e);return f.join("&")};d.fn.extend({serialize:function(){return d.param(this.serializeArray())},serializeArray:function(){return this.map(function(){var a=d.prop(this,"elements");return a?d.makeArray(a):this}).filter(function(){var a=this.type;
return this.name&&!d(this).is(":disabled")&&uc.test(this.nodeName)&&!tc.test(a)&&(this.checked||!zb.test(a))}).map(function(a,b){a=d(this).val();return null==a?null:Array.isArray(a)?d.map(a,function(a){return{name:b.name,value:a.replace(Gb,"\r\n")}}):{name:b.name,value:a.replace(Gb,"\r\n")}}).get()}});var vc=/%20/g,wc=/#.*$/,xc=/([?&])_=[^&]*/,yc=/^(.*?):[ \t]*([^\r\n]*)$/gm,zc=/^(?:GET|HEAD)$/,Ac=/^\/\//,Hb={},Qa={},Ib="*/".concat("*"),Va=B.createElement("a");Va.href=pa.href;d.extend({active:0,lastModified:{},
etag:{},ajaxSettings:{url:pa.href,type:"GET",isLocal:/^(?:about|app|app-storage|.+-extension|file|res|widget):$/.test(pa.protocol),global:!0,processData:!0,async:!0,contentType:"application/x-www-form-urlencoded; charset=UTF-8",accepts:{"*":Ib,text:"text/plain",html:"text/html",xml:"application/xml, text/xml",json:"application/json, text/javascript"},contents:{xml:/\bxml\b/,html:/\bhtml/,json:/\bjson\b/},responseFields:{xml:"responseXML",text:"responseText",json:"responseJSON"},converters:{"* text":String,
"text html":!0,"text json":JSON.parse,"text xml":d.parseXML},flatOptions:{url:!0,context:!0}},ajaxSetup:function(a,b){return b?Ra(Ra(a,d.ajaxSettings),b):Ra(d.ajaxSettings,a)},ajaxPrefilter:pb(Hb),ajaxTransport:pb(Qa),ajax:function(a,b){function c(a,b,c,g){var l,m,t,n=b;if(!G){G=!0;k&&u.clearTimeout(k);f=void 0;e=g||"";E.readyState=0<a?4:0;g=200<=a&&300>a||304===a;if(c){var w=p;for(var y=E,x,B,I,F,J=w.contents,M=w.dataTypes;"*"===M[0];)M.shift(),void 0===x&&(x=w.mimeType||y.getResponseHeader("Content-Type"));
if(x)for(B in J)if(J[B]&&J[B].test(x)){M.unshift(B);break}if(M[0]in c)I=M[0];else{for(B in c){if(!M[0]||w.converters[B+" "+M[0]]){I=B;break}F||(F=B)}I=I||F}c=I?(I!==M[0]&&M.unshift(I),c[I]):void 0;w=c}a:{c=p;x=w;B=E;I=g;var H,Z,K;w={};y=c.dataTypes.slice();if(y[1])for(H in c.converters)w[H.toLowerCase()]=c.converters[H];for(F=y.shift();F;)if(c.responseFields[F]&&(B[c.responseFields[F]]=x),!K&&I&&c.dataFilter&&(x=c.dataFilter(x,c.dataType)),K=F,F=y.shift())if("*"===F)F=K;else if("*"!==K&&K!==F){if(!(H=
w[K+" "+F]||w["* "+F]))for(N in w)if((Z=N.split(" "))[1]===F&&(H=w[K+" "+Z[0]]||w["* "+Z[0]])){!0===H?H=w[N]:!0!==w[N]&&(F=Z[0],y.unshift(Z[1]));break}if(!0!==H)if(H&&c["throws"])x=H(x);else try{x=H(x)}catch(bc){var N={state:"parsererror",error:H?bc:"No conversion from "+K+" to "+F};break a}}N={state:"success",data:x}}w=N;g?(p.ifModified&&((t=E.getResponseHeader("Last-Modified"))&&(d.lastModified[z]=t),(t=E.getResponseHeader("etag"))&&(d.etag[z]=t)),204===a||"HEAD"===p.type?n="nocontent":304===a?
n="notmodified":(n=w.state,l=w.data,g=!(m=w.error))):(m=n,!a&&n||(n="error",0>a&&(a=0)));E.status=a;E.statusText=(b||n)+"";g?v.resolveWith(q,[l,n,E]):v.rejectWith(q,[E,n,m]);E.statusCode(C);C=void 0;h&&r.trigger(g?"ajaxSuccess":"ajaxError",[E,p,g?l:m]);A.fireWith(q,[E,n]);h&&(r.trigger("ajaxComplete",[E,p]),--d.active||d.event.trigger("ajaxStop"))}}"object"==typeof a&&(b=a,a=void 0);b=b||{};var f,e,g,k,h,m,n,p=d.ajaxSetup({},b),q=p.context||p,r=p.context&&(q.nodeType||q.jquery)?d(q):d.event,v=d.Deferred(),
A=d.Callbacks("once memory"),C=p.statusCode||{},w={},y={},x="canceled",E={readyState:0,getResponseHeader:function(a){var b;if(G){if(!g)for(g={};b=yc.exec(e);)g[b[1].toLowerCase()]=b[2];b=g[a.toLowerCase()]}return null==b?null:b},getAllResponseHeaders:function(){return G?e:null},setRequestHeader:function(a,b){return null==G&&(a=y[a.toLowerCase()]=y[a.toLowerCase()]||a,w[a]=b),this},overrideMimeType:function(a){return null==G&&(p.mimeType=a),this},statusCode:function(a){var b;if(a)if(G)E.always(a[E.status]);
else for(b in a)C[b]=[C[b],a[b]];return this},abort:function(a){a=a||x;return f&&f.abort(a),c(0,a),this}};if(v.promise(E),p.url=((a||p.url||pa.href)+"").replace(Ac,pa.protocol+"//"),p.type=b.method||b.type||p.method||p.type,p.dataTypes=(p.dataType||"*").toLowerCase().match(N)||[""],null==p.crossDomain){a=B.createElement("a");try{a.href=p.url,a.href=a.href,p.crossDomain=Va.protocol+"//"+Va.host!=a.protocol+"//"+a.host}catch(Z){p.crossDomain=!0}}if(p.data&&p.processData&&"string"!=typeof p.data&&(p.data=
d.param(p.data,p.traditional)),qb(Hb,p,b,E),G)return E;(h=d.event&&p.global)&&0==d.active++&&d.event.trigger("ajaxStart");p.type=p.type.toUpperCase();p.hasContent=!zc.test(p.type);var z=p.url.replace(wc,"");p.hasContent?p.data&&p.processData&&0===(p.contentType||"").indexOf("application/x-www-form-urlencoded")&&(p.data=p.data.replace(vc,"+")):(n=p.url.slice(z.length),p.data&&(p.processData||"string"==typeof p.data)&&(z+=(Ua.test(z)?"&":"?")+p.data,delete p.data),!1===p.cache&&(z=z.replace(xc,"$1"),
n=(Ua.test(z)?"&":"?")+"_="+Fb++ +n),p.url=z+n);p.ifModified&&(d.lastModified[z]&&E.setRequestHeader("If-Modified-Since",d.lastModified[z]),d.etag[z]&&E.setRequestHeader("If-None-Match",d.etag[z]));(p.data&&p.hasContent&&!1!==p.contentType||b.contentType)&&E.setRequestHeader("Content-Type",p.contentType);E.setRequestHeader("Accept",p.dataTypes[0]&&p.accepts[p.dataTypes[0]]?p.accepts[p.dataTypes[0]]+("*"!==p.dataTypes[0]?", "+Ib+"; q=0.01":""):p.accepts["*"]);for(m in p.headers)E.setRequestHeader(m,
p.headers[m]);if(p.beforeSend&&(!1===p.beforeSend.call(q,E,p)||G))return E.abort();if(x="abort",A.add(p.complete),E.done(p.success),E.fail(p.error),f=qb(Qa,p,b,E)){if(E.readyState=1,h&&r.trigger("ajaxSend",[E,p]),G)return E;p.async&&0<p.timeout&&(k=u.setTimeout(function(){E.abort("timeout")},p.timeout));try{var G=!1;f.send(w,c)}catch(Z){if(G)throw Z;c(-1,Z)}}else c(-1,"No Transport");return E},getJSON:function(a,b,c){return d.get(a,b,c,"json")},getScript:function(a,b){return d.get(a,void 0,b,"script")}});
d.each(["get","post"],function(a,b){d[b]=function(a,f,e,g){return A(f)&&(g=g||e,e=f,f=void 0),d.ajax(d.extend({url:a,type:b,dataType:g,data:f,success:e},d.isPlainObject(a)&&a))}});d._evalUrl=function(a){return d.ajax({url:a,type:"GET",dataType:"script",cache:!0,async:!1,global:!1,"throws":!0})};d.fn.extend({wrapAll:function(a){var b;return this[0]&&(A(a)&&(a=a.call(this[0])),b=d(a,this[0].ownerDocument).eq(0).clone(!0),this[0].parentNode&&b.insertBefore(this[0]),b.map(function(){for(var a=this;a.firstElementChild;)a=
a.firstElementChild;return a}).append(this)),this},wrapInner:function(a){return A(a)?this.each(function(b){d(this).wrapInner(a.call(this,b))}):this.each(function(){var b=d(this),c=b.contents();c.length?c.wrapAll(a):b.append(a)})},wrap:function(a){var b=A(a);return this.each(function(c){d(this).wrapAll(b?a.call(this,c):a)})},unwrap:function(a){return this.parent(a).not("body").each(function(){d(this).replaceWith(this.childNodes)}),this}});d.expr.pseudos.hidden=function(a){return!d.expr.pseudos.visible(a)};
d.expr.pseudos.visible=function(a){return!!(a.offsetWidth||a.offsetHeight||a.getClientRects().length)};d.ajaxSettings.xhr=function(){try{return new u.XMLHttpRequest}catch(a){}};var Bc={0:200,1223:204},wa=d.ajaxSettings.xhr();H.cors=!!wa&&"withCredentials"in wa;H.ajax=wa=!!wa;d.ajaxTransport(function(a){var b,c;if(H.cors||wa&&!a.crossDomain)return{send:function(d,e){var f,h=a.xhr();if(h.open(a.type,a.url,a.async,a.username,a.password),a.xhrFields)for(f in a.xhrFields)h[f]=a.xhrFields[f];a.mimeType&&
h.overrideMimeType&&h.overrideMimeType(a.mimeType);a.crossDomain||d["X-Requested-With"]||(d["X-Requested-With"]="XMLHttpRequest");for(f in d)h.setRequestHeader(f,d[f]);b=function(a){return function(){b&&(b=c=h.onload=h.onerror=h.onabort=h.ontimeout=h.onreadystatechange=null,"abort"===a?h.abort():"error"===a?"number"!=typeof h.status?e(0,"error"):e(h.status,h.statusText):e(Bc[h.status]||h.status,h.statusText,"text"!==(h.responseType||"text")||"string"!=typeof h.responseText?{binary:h.response}:{text:h.responseText},
h.getAllResponseHeaders()))}};h.onload=b();c=h.onerror=h.ontimeout=b("error");void 0!==h.onabort?h.onabort=c:h.onreadystatechange=function(){4===h.readyState&&u.setTimeout(function(){b&&c()})};b=b("abort");try{h.send(a.hasContent&&a.data||null)}catch(l){if(b)throw l;}},abort:function(){b&&b()}}});d.ajaxPrefilter(function(a){a.crossDomain&&(a.contents.script=!1)});d.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},contents:{script:/\b(?:java|ecma)script\b/},
converters:{"text script":function(a){return d.globalEval(a),a}}});d.ajaxPrefilter("script",function(a){void 0===a.cache&&(a.cache=!1);a.crossDomain&&(a.type="GET")});d.ajaxTransport("script",function(a){if(a.crossDomain){var b,c;return{send:function(f,e){b=d("<script>").prop({charset:a.scriptCharset,src:a.url}).on("load error",c=function(a){b.remove();c=null;a&&e("error"===a.type?404:200,a.type)});B.head.appendChild(b[0])},abort:function(){c&&c()}}}});var Jb=[],Wa=/(=)\?(?=&|$)|\?\?/;d.ajaxSetup({jsonp:"callback",
jsonpCallback:function(){var a=Jb.pop()||d.expando+"_"+Fb++;return this[a]=!0,a}});d.ajaxPrefilter("json jsonp",function(a,b,c){var f,e,g,h=!1!==a.jsonp&&(Wa.test(a.url)?"url":"string"==typeof a.data&&0===(a.contentType||"").indexOf("application/x-www-form-urlencoded")&&Wa.test(a.data)&&"data");if(h||"jsonp"===a.dataTypes[0])return f=a.jsonpCallback=A(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback,h?a[h]=a[h].replace(Wa,"$1"+f):!1!==a.jsonp&&(a.url+=(Ua.test(a.url)?"&":"?")+a.jsonp+"="+f),a.converters["script json"]=
function(){return g||d.error(f+" was not called"),g[0]},a.dataTypes[0]="json",e=u[f],u[f]=function(){g=arguments},c.always(function(){void 0===e?d(u).removeProp(f):u[f]=e;a[f]&&(a.jsonpCallback=b.jsonpCallback,Jb.push(f));g&&A(e)&&e(g[0]);g=e=void 0}),"script"});H.createHTMLDocument=function(){var a=B.implementation.createHTMLDocument("").body;return a.innerHTML="<form></form><form></form>",2===a.childNodes.length}();d.parseHTML=function(a,b,c){if("string"!=typeof a)return[];"boolean"==typeof b&&
(c=b,b=!1);var f,e,g;return b||(H.createHTMLDocument?((f=(b=B.implementation.createHTMLDocument("")).createElement("base")).href=B.location.href,b.head.appendChild(f)):b=B),e=wb.exec(a),g=!c&&[],e?[b.createElement(e[1])]:(e=$a([a],b,g),g&&g.length&&d(g).remove(),d.merge([],e.childNodes))};d.fn.load=function(a,b,c){var f,e,g,h=this,l=a.indexOf(" ");return-1<l&&(f=ja(a.slice(l)),a=a.slice(0,l)),A(b)?(c=b,b=void 0):b&&"object"==typeof b&&(e="POST"),0<h.length&&d.ajax({url:a,type:e||"GET",dataType:"html",
data:b}).done(function(a){g=arguments;h.html(f?d("<div>").append(d.parseHTML(a)).find(f):a)}).always(c&&function(a,b){h.each(function(){c.apply(this,g||[a.responseText,b,a])})}),this};d.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){d.fn[b]=function(a){return this.on(b,a)}});d.expr.pseudos.animated=function(a){return d.grep(d.timers,function(b){return a===b.elem}).length};d.offset={setOffset:function(a,b,c){var f,e,g,h=d.css(a,"position"),l=d(a),m={};
"static"===h&&(a.style.position="relative");var n=l.offset();var p=d.css(a,"top");var q=d.css(a,"left");("absolute"===h||"fixed"===h)&&-1<(p+q).indexOf("auto")?(g=(f=l.position()).top,e=f.left):(g=parseFloat(p)||0,e=parseFloat(q)||0);A(b)&&(b=b.call(a,c,d.extend({},n)));null!=b.top&&(m.top=b.top-n.top+g);null!=b.left&&(m.left=b.left-n.left+e);"using"in b?b.using.call(a,m):l.css(m)}};d.fn.extend({offset:function(a){if(arguments.length)return void 0===a?this:this.each(function(b){d.offset.setOffset(this,
a,b)});var b,c,f=this[0];if(f)return f.getClientRects().length?(b=f.getBoundingClientRect(),c=f.ownerDocument.defaultView,{top:b.top+c.pageYOffset,left:b.left+c.pageXOffset}):{top:0,left:0}},position:function(){if(this[0]){var a,b=this[0],c={top:0,left:0};if("fixed"===d.css(b,"position"))var f=b.getBoundingClientRect();else{f=this.offset();var e=b.ownerDocument;for(a=b.offsetParent||e.documentElement;a&&(a===e.body||a===e.documentElement)&&"static"===d.css(a,"position");)a=a.parentNode;a&&a!==b&&
1===a.nodeType&&((c=d(a).offset()).top+=d.css(a,"borderTopWidth",!0),c.left+=d.css(a,"borderLeftWidth",!0))}return{top:f.top-c.top-d.css(b,"marginTop",!0),left:f.left-c.left-d.css(b,"marginLeft",!0)}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent;a&&"static"===d.css(a,"position");)a=a.offsetParent;return a||Ia})}});d.each({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},function(a,b){var c="pageYOffset"===b;d.fn[a]=function(d){return ha(this,function(a,d,f){var e;
if(qa(a)?e=a:9===a.nodeType&&(e=a.defaultView),void 0===f)return e?e[b]:a[d];e?e.scrollTo(c?e.pageXOffset:f,c?f:e.pageYOffset):a[d]=f},a,d,arguments.length)}});d.each(["top","left"],function(a,b){d.cssHooks[b]=hb(H.pixelPosition,function(a,f){if(f)return f=ca(a,b),La.test(f)?d(a).position()[b]+"px":f})});d.each({Height:"height",Width:"width"},function(a,b){d.each({padding:"inner"+a,content:b,"":"outer"+a},function(c,f){d.fn[f]=function(e,g){var h=arguments.length&&(c||"boolean"!=typeof e),l=c||(!0===
e||!0===g?"margin":"border");return ha(this,function(b,c,e){var g;return qa(b)?0===f.indexOf("outer")?b["inner"+a]:b.document.documentElement["client"+a]:9===b.nodeType?(g=b.documentElement,Math.max(b.body["scroll"+a],g["scroll"+a],b.body["offset"+a],g["offset"+a],g["client"+a])):void 0===e?d.css(b,c,l):d.style(b,c,e,l)},b,h?e:void 0,h)}})});d.each("blur focus focusin focusout resize scroll click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup contextmenu".split(" "),
function(a,b){d.fn[b]=function(a,d){return 0<arguments.length?this.on(b,null,a,d):this.trigger(b)}});d.fn.extend({hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});d.fn.extend({bind:function(a,b,c){return this.on(a,null,b,c)},unbind:function(a,b){return this.off(a,null,b)},delegate:function(a,b,c,d){return this.on(b,a,c,d)},undelegate:function(a,b,c){return 1===arguments.length?this.off(a,"**"):this.off(b,a||"**",c)}});d.proxy=function(a,b){var c,f,e;if("string"==typeof b&&(c=a[b],
b=a,a=c),A(a))return f=aa.call(arguments,2),e=function(){return a.apply(b||this,f.concat(aa.call(arguments)))},e.guid=a.guid=a.guid||d.guid++,e};d.holdReady=function(a){a?d.readyWait++:d.ready(!0)};d.isArray=Array.isArray;d.parseJSON=JSON.parse;d.nodeName=x;d.isFunction=A;d.isWindow=qa;d.camelCase=n;d.type=z;d.now=Date.now;d.isNumeric=function(a){var b=d.type(a);return("number"===b||"string"===b)&&!isNaN(a-parseFloat(a))};"function"==typeof define&&define.amd&&define("jquery",[],function(){return d});
var Cc=u.jQuery,Dc=u.$;return d.noConflict=function(a){return u.$===d&&(u.$=Dc),a&&u.jQuery===d&&(u.jQuery=Cc),d},w||(u.jQuery=u.$=d),d});/*
 http://www.gnu.org/licenses/gpl.html [GNU General Public License]
 @param {jQuery} {md5:function(string))
 @return string
*/
(function(u){var w=function(h,u){var m=h&2147483648;var q=u&2147483648;var E=h&1073741824;var w=u&1073741824;h=(h&1073741823)+(u&1073741823);return E&w?h^2147483648^m^q:E|w?h&1073741824?h^3221225472^m^q:h^1073741824^m^q:h^m^q},J=function(h,u,m,q,x,y,z){h=w(h,w(w(u&m|~u&q,x),z));return w(h<<y|h>>>32-y,u)},z=function(h,u,m,q,x,y,z){h=w(h,w(w(u&q|m&~q,x),z));return w(h<<y|h>>>32-y,u)},y=function(h,u,m,q,x,y,z){h=w(h,w(w(u^m^q,x),z));return w(h<<y|h>>>32-y,u)},x=function(h,u,m,q,x,y,z){h=w(h,w(w(m^(u|
~q),x),z));return w(h<<y|h>>>32-y,u)},Q=function(h){var u="",m;for(m=0;3>=m;m++){var q=h>>>8*m&255;q="0"+q.toString(16);u+=q.substr(q.length-2,2)}return u};u.extend({md5:function(h){var u,m;h=h.replace(/\x0d\x0a/g,"\n");var q="";for(u=0;u<h.length;u++){var F=h.charCodeAt(u);128>F?q+=String.fromCharCode(F):(127<F&&2048>F?q+=String.fromCharCode(F>>6|192):(q+=String.fromCharCode(F>>12|224),q+=String.fromCharCode(F>>6&63|128)),q+=String.fromCharCode(F&63|128))}u=q.length;h=u+8;var M=16*((h-h%64)/64+1);
h=Array(M-1);for(m=0;m<u;){F=(m-m%4)/4;var ia=m%4*8;h[F]|=q.charCodeAt(m)<<ia;m++}F=(m-m%4)/4;h[F]|=128<<m%4*8;h[M-2]=u<<3;h[M-1]=u>>>29;m=1732584193;var n=4023233417;var r=2562383102;var v=271733878;for(q=0;q<h.length;q+=16)u=m,F=n,M=r,ia=v,m=J(m,n,r,v,h[q+0],7,3614090360),v=J(v,m,n,r,h[q+1],12,3905402710),r=J(r,v,m,n,h[q+2],17,606105819),n=J(n,r,v,m,h[q+3],22,3250441966),m=J(m,n,r,v,h[q+4],7,4118548399),v=J(v,m,n,r,h[q+5],12,1200080426),r=J(r,v,m,n,h[q+6],17,2821735955),n=J(n,r,v,m,h[q+7],22,4249261313),
m=J(m,n,r,v,h[q+8],7,1770035416),v=J(v,m,n,r,h[q+9],12,2336552879),r=J(r,v,m,n,h[q+10],17,4294925233),n=J(n,r,v,m,h[q+11],22,2304563134),m=J(m,n,r,v,h[q+12],7,1804603682),v=J(v,m,n,r,h[q+13],12,4254626195),r=J(r,v,m,n,h[q+14],17,2792965006),n=J(n,r,v,m,h[q+15],22,1236535329),m=z(m,n,r,v,h[q+1],5,4129170786),v=z(v,m,n,r,h[q+6],9,3225465664),r=z(r,v,m,n,h[q+11],14,643717713),n=z(n,r,v,m,h[q+0],20,3921069994),m=z(m,n,r,v,h[q+5],5,3593408605),v=z(v,m,n,r,h[q+10],9,38016083),r=z(r,v,m,n,h[q+15],14,3634488961),
n=z(n,r,v,m,h[q+4],20,3889429448),m=z(m,n,r,v,h[q+9],5,568446438),v=z(v,m,n,r,h[q+14],9,3275163606),r=z(r,v,m,n,h[q+3],14,4107603335),n=z(n,r,v,m,h[q+8],20,1163531501),m=z(m,n,r,v,h[q+13],5,2850285829),v=z(v,m,n,r,h[q+2],9,4243563512),r=z(r,v,m,n,h[q+7],14,1735328473),n=z(n,r,v,m,h[q+12],20,2368359562),m=y(m,n,r,v,h[q+5],4,4294588738),v=y(v,m,n,r,h[q+8],11,2272392833),r=y(r,v,m,n,h[q+11],16,1839030562),n=y(n,r,v,m,h[q+14],23,4259657740),m=y(m,n,r,v,h[q+1],4,2763975236),v=y(v,m,n,r,h[q+4],11,1272893353),
r=y(r,v,m,n,h[q+7],16,4139469664),n=y(n,r,v,m,h[q+10],23,3200236656),m=y(m,n,r,v,h[q+13],4,681279174),v=y(v,m,n,r,h[q+0],11,3936430074),r=y(r,v,m,n,h[q+3],16,3572445317),n=y(n,r,v,m,h[q+6],23,76029189),m=y(m,n,r,v,h[q+9],4,3654602809),v=y(v,m,n,r,h[q+12],11,3873151461),r=y(r,v,m,n,h[q+15],16,530742520),n=y(n,r,v,m,h[q+2],23,3299628645),m=x(m,n,r,v,h[q+0],6,4096336452),v=x(v,m,n,r,h[q+7],10,1126891415),r=x(r,v,m,n,h[q+14],15,2878612391),n=x(n,r,v,m,h[q+5],21,4237533241),m=x(m,n,r,v,h[q+12],6,1700485571),
v=x(v,m,n,r,h[q+3],10,2399980690),r=x(r,v,m,n,h[q+10],15,4293915773),n=x(n,r,v,m,h[q+1],21,2240044497),m=x(m,n,r,v,h[q+8],6,1873313359),v=x(v,m,n,r,h[q+15],10,4264355552),r=x(r,v,m,n,h[q+6],15,2734768916),n=x(n,r,v,m,h[q+13],21,1309151649),m=x(m,n,r,v,h[q+4],6,4149444226),v=x(v,m,n,r,h[q+11],10,3174756917),r=x(r,v,m,n,h[q+2],15,718787259),n=x(n,r,v,m,h[q+9],21,3951481745),m=w(m,u),n=w(n,F),r=w(r,M),v=w(v,ia);return(Q(m)+Q(n)+Q(r)+Q(v)).toLowerCase()}})})(jQuery);
